/*
Copyright 2026 Apoxy, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	vpcv1alpha1 "github.com/apoxy-dev/apoxy/api/vpc/v1alpha1"
	scheme "github.com/apoxy-dev/apoxy/client/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// RelaysGetter has a method to return a RelayInterface.
// A group's client should implement this interface.
type RelaysGetter interface {
	Relays() RelayInterface
}

// RelayInterface has methods to work with Relay resources.
type RelayInterface interface {
	Create(ctx context.Context, relay *vpcv1alpha1.Relay, opts v1.CreateOptions) (*vpcv1alpha1.Relay, error)
	Update(ctx context.Context, relay *vpcv1alpha1.Relay, opts v1.UpdateOptions) (*vpcv1alpha1.Relay, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, relay *vpcv1alpha1.Relay, opts v1.UpdateOptions) (*vpcv1alpha1.Relay, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*vpcv1alpha1.Relay, error)
	List(ctx context.Context, opts v1.ListOptions) (*vpcv1alpha1.RelayList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *vpcv1alpha1.Relay, err error)
	RelayExpansion
}

// relays implements RelayInterface
type relays struct {
	*gentype.ClientWithList[*vpcv1alpha1.Relay, *vpcv1alpha1.RelayList]
}

// newRelays returns a Relays
func newRelays(c *VpcV1alpha1Client) *relays {
	return &relays{
		gentype.NewClientWithList[*vpcv1alpha1.Relay, *vpcv1alpha1.RelayList](
			"relays",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *vpcv1alpha1.Relay { return &vpcv1alpha1.Relay{} },
			func() *vpcv1alpha1.RelayList { return &vpcv1alpha1.RelayList{} },
		),
	}
}
