/*
Copyright 2026 Apoxy, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	vpcv1alpha1 "github.com/apoxy-dev/apoxy/api/vpc/v1alpha1"
	scheme "github.com/apoxy-dev/apoxy/client/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// VPCServicesGetter has a method to return a VPCServiceInterface.
// A group's client should implement this interface.
type VPCServicesGetter interface {
	VPCServices() VPCServiceInterface
}

// VPCServiceInterface has methods to work with VPCService resources.
type VPCServiceInterface interface {
	Create(ctx context.Context, vPCService *vpcv1alpha1.VPCService, opts v1.CreateOptions) (*vpcv1alpha1.VPCService, error)
	Update(ctx context.Context, vPCService *vpcv1alpha1.VPCService, opts v1.UpdateOptions) (*vpcv1alpha1.VPCService, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, vPCService *vpcv1alpha1.VPCService, opts v1.UpdateOptions) (*vpcv1alpha1.VPCService, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*vpcv1alpha1.VPCService, error)
	List(ctx context.Context, opts v1.ListOptions) (*vpcv1alpha1.VPCServiceList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *vpcv1alpha1.VPCService, err error)
	VPCServiceExpansion
}

// vPCServices implements VPCServiceInterface
type vPCServices struct {
	*gentype.ClientWithList[*vpcv1alpha1.VPCService, *vpcv1alpha1.VPCServiceList]
}

// newVPCServices returns a VPCServices
func newVPCServices(c *VpcV1alpha1Client) *vPCServices {
	return &vPCServices{
		gentype.NewClientWithList[*vpcv1alpha1.VPCService, *vpcv1alpha1.VPCServiceList](
			"vpcservices",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *vpcv1alpha1.VPCService { return &vpcv1alpha1.VPCService{} },
			func() *vpcv1alpha1.VPCServiceList { return &vpcv1alpha1.VPCServiceList{} },
		),
	}
}
