/*
Copyright 2025 Apoxy, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha2

import (
	"context"
	"time"

	v1alpha2 "github.com/apoxy-dev/apoxy/api/core/v1alpha2"
	scheme "github.com/apoxy-dev/apoxy/client/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// TLSCertificatesGetter has a method to return a TLSCertificateInterface.
// A group's client should implement this interface.
type TLSCertificatesGetter interface {
	TLSCertificates() TLSCertificateInterface
}

// TLSCertificateInterface has methods to work with TLSCertificate resources.
type TLSCertificateInterface interface {
	Create(ctx context.Context, tLSCertificate *v1alpha2.TLSCertificate, opts v1.CreateOptions) (*v1alpha2.TLSCertificate, error)
	Update(ctx context.Context, tLSCertificate *v1alpha2.TLSCertificate, opts v1.UpdateOptions) (*v1alpha2.TLSCertificate, error)
	UpdateStatus(ctx context.Context, tLSCertificate *v1alpha2.TLSCertificate, opts v1.UpdateOptions) (*v1alpha2.TLSCertificate, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha2.TLSCertificate, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha2.TLSCertificateList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha2.TLSCertificate, err error)
	TLSCertificateExpansion
}

// tLSCertificates implements TLSCertificateInterface
type tLSCertificates struct {
	client rest.Interface
}

// newTLSCertificates returns a TLSCertificates
func newTLSCertificates(c *CoreV1alpha2Client) *tLSCertificates {
	return &tLSCertificates{
		client: c.RESTClient(),
	}
}

// Get takes name of the tLSCertificate, and returns the corresponding tLSCertificate object, and an error if there is any.
func (c *tLSCertificates) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha2.TLSCertificate, err error) {
	result = &v1alpha2.TLSCertificate{}
	err = c.client.Get().
		Resource("tlscertificates").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of TLSCertificates that match those selectors.
func (c *tLSCertificates) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha2.TLSCertificateList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha2.TLSCertificateList{}
	err = c.client.Get().
		Resource("tlscertificates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested tLSCertificates.
func (c *tLSCertificates) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("tlscertificates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a tLSCertificate and creates it.  Returns the server's representation of the tLSCertificate, and an error, if there is any.
func (c *tLSCertificates) Create(ctx context.Context, tLSCertificate *v1alpha2.TLSCertificate, opts v1.CreateOptions) (result *v1alpha2.TLSCertificate, err error) {
	result = &v1alpha2.TLSCertificate{}
	err = c.client.Post().
		Resource("tlscertificates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(tLSCertificate).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a tLSCertificate and updates it. Returns the server's representation of the tLSCertificate, and an error, if there is any.
func (c *tLSCertificates) Update(ctx context.Context, tLSCertificate *v1alpha2.TLSCertificate, opts v1.UpdateOptions) (result *v1alpha2.TLSCertificate, err error) {
	result = &v1alpha2.TLSCertificate{}
	err = c.client.Put().
		Resource("tlscertificates").
		Name(tLSCertificate.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(tLSCertificate).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *tLSCertificates) UpdateStatus(ctx context.Context, tLSCertificate *v1alpha2.TLSCertificate, opts v1.UpdateOptions) (result *v1alpha2.TLSCertificate, err error) {
	result = &v1alpha2.TLSCertificate{}
	err = c.client.Put().
		Resource("tlscertificates").
		Name(tLSCertificate.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(tLSCertificate).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the tLSCertificate and deletes it. Returns an error if one occurs.
func (c *tLSCertificates) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("tlscertificates").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *tLSCertificates) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("tlscertificates").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched tLSCertificate.
func (c *tLSCertificates) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha2.TLSCertificate, err error) {
	result = &v1alpha2.TLSCertificate{}
	err = c.client.Patch(pt).
		Resource("tlscertificates").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
