// SPDX-License-Identifier: AGPL-3.0-only

// protoc-gen-go-vpcrpc generates typed clients and servers for the
// github.com/apoxy-dev/apoxy/pkg/vpc/rpc runtime. Output files end in
// _vpcrpc.pb.go.
//
//	protoc --go_out=. --go-vpcrpc_out=. foo.proto
package main

import (
	"flag"
	"fmt"
	"os"
	"strconv"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/pluginpb"
)

const version = "0.1.0"

const (
	contextPkg = protogen.GoImportPath("context")
	rpcPkg     = protogen.GoImportPath("github.com/apoxy-dev/apoxy/pkg/vpc/rpc")
)

// syntaxField is the field number of "syntax" in FileDescriptorProto.
const syntaxField = 12

func main() {
	if len(os.Args) == 2 && os.Args[1] == "--version" {
		fmt.Println("protoc-gen-go-vpcrpc", version)
		return
	}
	var flags flag.FlagSet
	protogen.Options{ParamFunc: flags.Set}.Run(func(gen *protogen.Plugin) error {
		gen.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)
		for _, f := range gen.Files {
			if f.Generate && len(f.Services) > 0 {
				generateFile(gen, f)
			}
		}
		return nil
	})
}

func generateFile(gen *protogen.Plugin, file *protogen.File) {
	g := gen.NewGeneratedFile(file.GeneratedFilenamePrefix+"_vpcrpc.pb.go", file.GoImportPath)
	// Copy the comments above "syntax", for example a license line.
	loc := file.Desc.SourceLocations().ByPath(protoreflect.SourcePath{syntaxField})
	for _, c := range loc.LeadingDetachedComments {
		g.P(protogen.Comments(c))
		g.P()
	}
	g.P("// Code generated by protoc-gen-go-vpcrpc. DO NOT EDIT.")
	g.P("// versions:")
	g.P("// - protoc-gen-go-vpcrpc v", version)
	g.P("// - protoc               ", protocVersion(gen))
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	for _, s := range file.Services {
		generateService(g, s)
	}
}

func protocVersion(gen *protogen.Plugin) string {
	v := gen.Request.GetCompilerVersion()
	if v == nil {
		return "(unknown)"
	}
	s := fmt.Sprintf("v%d.%d.%d", v.GetMajor(), v.GetMinor(), v.GetPatch())
	if v.GetSuffix() != "" {
		s += "-" + v.GetSuffix()
	}
	return s
}

func methodConst(s *protogen.Service, m *protogen.Method) string {
	return s.GoName + "_" + m.GoName + "_FullMethodName"
}

func generateService(g *protogen.GeneratedFile, s *protogen.Service) {
	ctx := g.QualifiedGoIdent(contextPkg.Ident("Context"))
	rpc := func(name string) string { return g.QualifiedGoIdent(rpcPkg.Ident(name)) }
	clientName, serverName := s.GoName+"Client", s.GoName+"Server"

	g.P("// Full method names of the ", s.GoName, " service.")
	g.P("const (")
	for _, m := range s.Methods {
		name := "/" + string(s.Desc.FullName()) + "/" + string(m.Desc.Name())
		g.P(methodConst(s, m), " = ", strconv.Quote(name))
	}
	g.P(")")
	g.P()

	// Client.
	g.P("// ", clientName, " is the client API of the ", s.GoName, " service.")
	g.P("type ", clientName, " interface {")
	for _, m := range s.Methods {
		g.P(m.Comments.Leading, m.GoName, clientSignature(g, m, ctx, rpc))
	}
	g.P("}")
	g.P()
	lower := unexport(clientName)
	g.P("type ", lower, " struct{ c ", rpc("Caller"), " }")
	g.P()
	g.P("// New", clientName, " returns a client of the ", s.GoName, " service that makes calls with c.")
	g.P("func New", clientName, "(c ", rpc("Caller"), ") ", clientName, " { return ", lower, "{c} }")
	g.P()
	for _, m := range s.Methods {
		in, out := g.QualifiedGoIdent(m.Input.GoIdent), g.QualifiedGoIdent(m.Output.GoIdent)
		g.P("func (c ", lower, ") ", m.GoName, clientSignature(g, m, ctx, rpc), " {")
		switch k := kind(m); k {
		case "Unary":
			g.P("out := new(", out, ")")
			g.P("if err := c.c.Invoke(ctx, ", methodConst(s, m), ", in, out); err != nil {")
			g.P("return nil, err")
			g.P("}")
			g.P("return out, nil")
		case "ServerStream":
			g.P("return ", rpc("OpenServerStream"), "[", out, "](ctx, c.c, ", methodConst(s, m), ", in)")
		default:
			g.P("return ", rpc("Open"+k), "[", in, ", ", out, "](ctx, c.c, ", methodConst(s, m), ")")
		}
		g.P("}")
		g.P()
	}

	// Server.
	g.P("// ", serverName, " is the server API of the ", s.GoName, " service.")
	g.P("type ", serverName, " interface {")
	for _, m := range s.Methods {
		g.P(m.Comments.Leading, m.GoName, serverSignature(g, m, ctx, rpc))
	}
	g.P("}")
	g.P()
	unimpl := "Unimplemented" + serverName
	g.P("// ", unimpl, " returns Unimplemented for each method. Embed it to add")
	g.P("// methods to the service without a build failure.")
	g.P("type ", unimpl, " struct{}")
	g.P()
	for _, m := range s.Methods {
		g.P("func (", unimpl, ") ", m.GoName, serverSignature(g, m, ctx, rpc), " {")
		err := rpc("Errorf") + "(" + rpc("Unimplemented") + `, "method ` + m.GoName + ` not implemented")`
		if m.Desc.IsStreamingServer() {
			g.P("return ", err)
		} else {
			g.P("return nil, ", err)
		}
		g.P("}")
		g.P()
	}
	g.P("// Register", serverName, " adds the methods of srv to m.")
	g.P("func Register", serverName, "(m *", rpc("Mux"), ", srv ", serverName, ") {")
	for _, m := range s.Methods {
		g.P(rpc("Handle"+kind(m)), "(m, ", methodConst(s, m), ", srv.", m.GoName, ")")
	}
	g.P("}")
	g.P()
}

// kind returns the call kind of m, as named in the rpc Open* and Handle* functions.
func kind(m *protogen.Method) string {
	switch cs, ss := m.Desc.IsStreamingClient(), m.Desc.IsStreamingServer(); {
	case !cs && !ss:
		return "Unary"
	case !cs:
		return "ServerStream"
	case !ss:
		return "ClientStream"
	}
	return "BidiStream"
}

func clientSignature(g *protogen.GeneratedFile, m *protogen.Method, ctx string, rpc func(string) string) string {
	in, out := g.QualifiedGoIdent(m.Input.GoIdent), g.QualifiedGoIdent(m.Output.GoIdent)
	switch kind(m) {
	case "Unary":
		return "(ctx " + ctx + ", in *" + in + ") (*" + out + ", error)"
	case "ServerStream":
		return "(ctx " + ctx + ", in *" + in + ") (" + rpc("ServerStreamClient") + "[" + out + "], error)"
	case "ClientStream":
		return "(ctx " + ctx + ") (" + rpc("ClientStreamClient") + "[" + in + ", " + out + "], error)"
	}
	return "(ctx " + ctx + ") (" + rpc("BidiStreamClient") + "[" + in + ", " + out + "], error)"
}

func serverSignature(g *protogen.GeneratedFile, m *protogen.Method, ctx string, rpc func(string) string) string {
	in, out := g.QualifiedGoIdent(m.Input.GoIdent), g.QualifiedGoIdent(m.Output.GoIdent)
	switch kind(m) {
	case "Unary":
		return "(" + ctx + ", *" + in + ") (*" + out + ", error)"
	case "ServerStream":
		return "(" + ctx + ", *" + in + ", " + rpc("ServerStreamServer") + "[" + out + "]) error"
	case "ClientStream":
		return "(" + ctx + ", " + rpc("ClientStreamServer") + "[" + in + "]) (*" + out + ", error)"
	}
	return "(" + ctx + ", " + rpc("BidiStreamServer") + "[" + in + ", " + out + "]) error"
}

func unexport(s string) string {
	if s == "" {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}
