/*
Copyright 2026 Apoxy, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	controllersv1alpha1 "github.com/apoxy-dev/apoxy/api/controllers/v1alpha1"
	scheme "github.com/apoxy-dev/apoxy/client/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ProxiesGetter has a method to return a ProxyInterface.
// A group's client should implement this interface.
type ProxiesGetter interface {
	Proxies() ProxyInterface
}

// ProxyInterface has methods to work with Proxy resources.
type ProxyInterface interface {
	Create(ctx context.Context, proxy *controllersv1alpha1.Proxy, opts v1.CreateOptions) (*controllersv1alpha1.Proxy, error)
	Update(ctx context.Context, proxy *controllersv1alpha1.Proxy, opts v1.UpdateOptions) (*controllersv1alpha1.Proxy, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, proxy *controllersv1alpha1.Proxy, opts v1.UpdateOptions) (*controllersv1alpha1.Proxy, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*controllersv1alpha1.Proxy, error)
	List(ctx context.Context, opts v1.ListOptions) (*controllersv1alpha1.ProxyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *controllersv1alpha1.Proxy, err error)
	ProxyExpansion
}

// proxies implements ProxyInterface
type proxies struct {
	*gentype.ClientWithList[*controllersv1alpha1.Proxy, *controllersv1alpha1.ProxyList]
}

// newProxies returns a Proxies
func newProxies(c *ControllersV1alpha1Client) *proxies {
	return &proxies{
		gentype.NewClientWithList[*controllersv1alpha1.Proxy, *controllersv1alpha1.ProxyList](
			"proxies",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *controllersv1alpha1.Proxy { return &controllersv1alpha1.Proxy{} },
			func() *controllersv1alpha1.ProxyList { return &controllersv1alpha1.ProxyList{} },
		),
	}
}
