// SPDX-License-Identifier: AGPL-3.0-only

package host

import (
	_ "embed"
	"encoding/json"
	"errors"
	"fmt"
	"regexp"
	"strings"

	computev1alpha1 "github.com/apoxy-dev/apoxy/api/compute/v1alpha1"
)

// Internal workerd identifiers used in the emitted config. These are
// platform-internal contracts, not user-visible.
const (
	// workerServiceName is the workerd service name for the worker.
	workerServiceName = "main"
	// assetsServiceName is the workerd disk service name for static assets.
	assetsServiceName = "assets"
	// assetsBindingName is the env binding the worker uses to reach assets
	// (env.ASSETS.fetch(...)).
	assetsBindingName = "ASSETS"
	// httpSocketName is the workerd socket name for the http socket.
	httpSocketName = "http"
)

// knownModuleFields is the set of workerd Worker.Module union fields. The
// compute ModuleType constants are authored to equal these field names 1:1
// (see api/compute/v1alpha1.ModuleType — "mirrors workerd's module union"),
// so the type string is emitted directly as the capnp field name.
var knownModuleFields = map[computev1alpha1.ModuleType]bool{
	computev1alpha1.ESModule:       true,
	computev1alpha1.CommonJSModule: true,
	computev1alpha1.TextModule:     true,
	computev1alpha1.DataModule:     true,
	computev1alpha1.JSONModule:     true,
	computev1alpha1.WasmModule:     true,
}

var (
	errNoCompatibilityDate = errors.New("workerd-host: compatibilityDate is required (workerd refuses to start without it)")
	errNoEntrypoint        = errors.New("workerd-host: bundle has no esModule entrypoint module")
)

// BuildInput is the input to BuildWorkerdConfig.
type BuildInput struct {
	// Manifest is the bundle's BundleManifest (modules + compat + assets).
	Manifest computev1alpha1.BundleManifest
	// Config is the revision's serving config (runtime overrides, bindings, env).
	Config computev1alpha1.ServiceConfigSpec
	// Socket is the listening socket workerd binds.
	Socket SocketSpec
	// AssetsDir is the in-jail absolute path the assets layer extracted to.
	// Used only when Manifest.AssetsPrefix is set.
	AssetsDir string
	// Secrets maps binding names (Binding.Name, for bindings of type secret)
	// to their resolved values. The caller resolves them from the referenced
	// SecretStores; rendering fails on a secret binding with no entry here.
	Secrets map[string]string
}

// BuildWorkerdConfig renders the textual capnp config that `workerd serve`
// consumes. It is a pure, deterministic function: identical input yields
// byte-identical output. Module `embed` paths are emitted relative to the
// config file, which the host co-locates with the extracted modules layer so
// each path is just Module.Path.
func BuildWorkerdConfig(in BuildInput) (string, error) {
	switch in.Socket.Kind {
	case HTTPSocket:
		// ok
	case FilterSocket:
		return "", errFilterSocketUnsupported
	default:
		return "", fmt.Errorf("workerd-host: unsupported socket kind %d", in.Socket.Kind)
	}

	compatDate := in.Manifest.CompatibilityDate
	if in.Config.Runtime != nil && in.Config.Runtime.CompatibilityDate != "" {
		compatDate = in.Config.Runtime.CompatibilityDate
	}
	if compatDate == "" {
		return "", errNoCompatibilityDate
	}

	modules, err := orderModules(in.Manifest.Modules)
	if err != nil {
		return "", err
	}

	bindings, err := buildBindings(in.Config, in.Secrets)
	if err != nil {
		return "", err
	}

	hasAssets := in.Manifest.AssetsPrefix != ""
	if hasAssets {
		bindings = append(bindings, binding{name: assetsBindingName, kind: bindingService, value: assetsServiceName})
	}

	flags := unionFlags(in.Manifest.CompatibilityFlags, runtimeFlags(in.Config))

	var b strings.Builder
	b.WriteString("# Generated by apoxy workerd-host. DO NOT EDIT.\n")
	b.WriteString(`using Workerd = import "/workerd/workerd.capnp";` + "\n\n")

	// Top-level Config: services + sockets.
	b.WriteString("const config :Workerd.Config = (\n")
	b.WriteString("  services = [\n")
	fmt.Fprintf(&b, "    (name = %s, worker = .mainWorker),\n", capnpStr(workerServiceName))
	if hasAssets {
		fmt.Fprintf(&b, "    (name = %s, disk = (path = %s, writable = false)),\n",
			capnpStr(assetsServiceName), capnpStr(in.AssetsDir))
	}
	b.WriteString("  ],\n")
	b.WriteString("  sockets = [\n")
	fmt.Fprintf(&b, "    (name = %s, address = %s, http = (), service = %s),\n",
		capnpStr(httpSocketName), capnpStr(in.Socket.Addr), capnpStr(workerServiceName))
	b.WriteString("  ],\n")
	b.WriteString(");\n\n")

	// The worker itself.
	b.WriteString("const mainWorker :Workerd.Worker = (\n")
	fmt.Fprintf(&b, "  compatibilityDate = %s,\n", capnpStr(compatDate))
	if len(flags) > 0 {
		fmt.Fprintf(&b, "  compatibilityFlags = [%s],\n", capnpStrList(flags))
	}
	b.WriteString("  modules = [\n")
	for _, m := range modules {
		fmt.Fprintf(&b, "    (name = %s, %s = embed %s),\n",
			capnpStr(m.Name), string(m.Type), capnpStr(m.Path))
	}
	b.WriteString("  ],\n")
	if len(bindings) > 0 {
		b.WriteString("  bindings = [\n")
		for _, bd := range bindings {
			switch bd.kind {
			case bindingText:
				fmt.Fprintf(&b, "    (name = %s, text = %s),\n", capnpStr(bd.name), capnpStr(bd.value))
			case bindingService:
				fmt.Fprintf(&b, "    (name = %s, service = %s),\n", capnpStr(bd.name), capnpStr(bd.value))
			default:
				return "", fmt.Errorf("workerd-host: unknown binding kind %q", bd.kind)
			}
		}
		b.WriteString("  ],\n")
	}
	b.WriteString(");\n")

	return b.String(), nil
}

// =============================================================================
// Resident dispatcher model (one shared workerd, many isolates via WorkerLoader).
//
// Unlike BuildWorkerdConfig (one baked worker per process, used by the
// single-resident cmd/workerd-host harness), the resident model runs ONE static
// dispatcher worker that loads customer isolates at runtime. BuildResidentConfig
// renders that dispatcher's static workerd config; BuildWorkerDefinition renders
// the per-isolate WorkerCode payload the manager serves to the dispatcher's
// WorkerLoader callback. See pkg/workerd/host/dispatcher.js and APO-796.
// =============================================================================

// dispatcherJS is the static dispatcher worker source, inlined into the resident
// config so no second file needs staging next to it.
//
//go:embed dispatcher.js
var dispatcherJS string

const (
	// dispatcherServiceName is the workerd service name for the dispatcher.
	dispatcherServiceName = "dispatcher"
	// managerServiceName is the workerd (external) service the dispatcher's
	// WorkerLoader callback fetches worker definitions from.
	managerServiceName = "manager"
	// loaderBindingName is the WorkerLoader binding env name (env.LOADER).
	loaderBindingName = "LOADER"
	// managerBindingName is the service binding env name (env.MANAGER).
	managerBindingName = "MANAGER"
	// dispatcherModuleName is the dispatcher's single module name.
	dispatcherModuleName = "dispatcher.js"
	// dispatcherCompatDate pins the dispatcher's own compatibility date. It is
	// independent of any customer worker's compatibilityDate.
	dispatcherCompatDate = "2025-06-01"
	// experimentalFlag is required to enable the workerLoader binding.
	experimentalFlag = "experimental"
	// globalOutboundServiceName is the workerd Network service that backs every
	// isolate's globalOutbound (the dispatcher passes the GLOBAL_OUTBOUND binding
	// to each WorkerLoader isolate). A `network` service means workerd runs its
	// own getaddrinfo + socket()/connect() for fetch() — a real, structural egress
	// the in-Sentry forwarder catches with the true (src,dst) and the host egress
	// bridge mediates. It must NEVER be an `external` service (one carrying an
	// address workerd dials directly): that flattens every destination to a single
	// endpoint before any syscall, blinding the forwarder. See
	// workerd-egress-encap.mdx §2.8.
	globalOutboundServiceName = "internet"
	// globalOutboundBindingName is the dispatcher env binding (env.GLOBAL_OUTBOUND)
	// the WorkerLoader callback passes as each isolate's globalOutbound.
	globalOutboundBindingName = "GLOBAL_OUTBOUND"
)

// globalOutboundAllow is the Network service allow set. It is deliberately broad:
// the host egress bridge — not workerd's own network filter — is the egress
// policy authority (allow/deny/SSRF/gateway/direct), and workerd must actually
// issue the connect() for the in-Sentry forwarder to catch and mediate it.
// Narrowing this would let workerd pre-empt a syscall the bridge needs to see.
// This exact set is validated end-to-end against stock workerd by the linux
// acceptance test (a real fetch() connect() caught by the forwarder).
var globalOutboundAllow = []string{"public", "private", "local", "network"}

// ResidentConfigInput is the input to BuildResidentConfig.
type ResidentConfigInput struct {
	// SocketAddr is the address the dispatcher's http socket binds — where the
	// inbound forwarder (APO-694) delivers Envoy's requests. workerd syntax:
	// "*:8080", "127.0.0.1:8080", or "unix:/path.sock".
	SocketAddr string
	// ManagerAddr is the address of the external manager service the dispatcher
	// fetches worker definitions from (the control channel). Typically a donated
	// AF_UNIX socket, e.g. "unix:/run/workerd-host/control.sock".
	ManagerAddr string
}

// BuildResidentConfig renders the static textual capnp config for the one
// resident workerd: a single dispatcher worker (WorkerLoader + manager service
// binding) behind the http socket. Pure and deterministic.
func BuildResidentConfig(in ResidentConfigInput) (string, error) {
	if in.SocketAddr == "" {
		return "", fmt.Errorf("workerd-host: resident config requires SocketAddr")
	}
	if in.ManagerAddr == "" {
		return "", fmt.Errorf("workerd-host: resident config requires ManagerAddr")
	}

	var b strings.Builder
	b.WriteString("# Generated by apoxy workerd-host (resident dispatcher). DO NOT EDIT.\n")
	b.WriteString(`using Workerd = import "/workerd/workerd.capnp";` + "\n\n")

	b.WriteString("const config :Workerd.Config = (\n")
	b.WriteString("  services = [\n")
	fmt.Fprintf(&b, "    (name = %s, worker = .dispatcher),\n", capnpStr(dispatcherServiceName))
	fmt.Fprintf(&b, "    (name = %s, external = (address = %s, http = ())),\n",
		capnpStr(managerServiceName), capnpStr(in.ManagerAddr))
	// The globalOutbound Network service (see globalOutboundServiceName): real
	// getaddrinfo + socket/connect for every isolate's fetch(), caught by the
	// in-Sentry forwarder and mediated by the host egress bridge.
	fmt.Fprintf(&b, "    (name = %s, network = (allow = [%s])),\n",
		capnpStr(globalOutboundServiceName), capnpStrList(globalOutboundAllow))
	b.WriteString("  ],\n")
	b.WriteString("  sockets = [\n")
	fmt.Fprintf(&b, "    (name = %s, address = %s, http = (), service = %s),\n",
		capnpStr(httpSocketName), capnpStr(in.SocketAddr), capnpStr(dispatcherServiceName))
	b.WriteString("  ],\n")
	b.WriteString(");\n\n")

	b.WriteString("const dispatcher :Workerd.Worker = (\n")
	fmt.Fprintf(&b, "  compatibilityDate = %s,\n", capnpStr(dispatcherCompatDate))
	fmt.Fprintf(&b, "  compatibilityFlags = [%s],\n", capnpStr(experimentalFlag))
	b.WriteString("  modules = [\n")
	fmt.Fprintf(&b, "    (name = %s, esModule = %s),\n", capnpStr(dispatcherModuleName), capnpStr(dispatcherJS))
	b.WriteString("  ],\n")
	b.WriteString("  bindings = [\n")
	fmt.Fprintf(&b, "    (name = %s, workerLoader = ()),\n", capnpStr(loaderBindingName))
	fmt.Fprintf(&b, "    (name = %s, service = %s),\n", capnpStr(managerBindingName), capnpStr(managerServiceName))
	// env.GLOBAL_OUTBOUND: the dispatcher passes this to each WorkerLoader isolate
	// as its globalOutbound (see dispatcher.js). It must resolve to the Network
	// service so egress stays structural.
	fmt.Fprintf(&b, "    (name = %s, service = %s),\n", capnpStr(globalOutboundBindingName), capnpStr(globalOutboundServiceName))
	b.WriteString("  ],\n")
	b.WriteString(");\n")

	cfg := b.String()
	// Self-check: fail loudly if a future edit ever points globalOutbound at an
	// address-carrying service (the §2.8 foot-gun) instead of the Network service.
	if err := validateGlobalOutbound(cfg); err != nil {
		return "", err
	}
	return cfg, nil
}

// globalOutboundBindingRE captures the service the GLOBAL_OUTBOUND env binding
// resolves to in an emitted resident config.
var globalOutboundBindingRE = regexp.MustCompile(
	`\(name = "` + globalOutboundBindingName + `", service = "([^"]+)"\)`)

// validateGlobalOutbound enforces the §2.8 structural-egress invariant on an
// emitted resident config: the service backing GLOBAL_OUTBOUND — hence every
// isolate's globalOutbound — must be a workerd `network` service (real
// getaddrinfo + socket/connect the in-Sentry forwarder catches). It must never
// be an `external` service, whose address workerd would dial directly, flattening
// every destination before any syscall and blinding the forwarder. It is run as a
// self-check on our own output and exercised directly by TestValidateGlobalOutbound.
func validateGlobalOutbound(cfg string) error {
	m := globalOutboundBindingRE.FindStringSubmatch(cfg)
	if m == nil {
		return fmt.Errorf("workerd-host: resident config has no %s binding; isolate egress would be dead", globalOutboundBindingName)
	}
	svc := m[1]
	kind, ok := serviceKind(cfg, svc)
	if !ok {
		return fmt.Errorf("workerd-host: resident config binds %s to undefined service %q", globalOutboundBindingName, svc)
	}
	if kind != "network" {
		return fmt.Errorf("workerd-host: %s must resolve to a `network` service for structural egress, got %q service %q (see workerd-egress-encap.mdx §2.8)", globalOutboundBindingName, kind, svc)
	}
	return nil
}

// serviceKind returns the workerd union field (network/external/worker/disk) of
// the service named svc in an emitted config, or false if svc is not declared.
func serviceKind(cfg, svc string) (string, bool) {
	re := regexp.MustCompile(`\(name = "` + regexp.QuoteMeta(svc) + `", (\w+) = `)
	m := re.FindStringSubmatch(cfg)
	if m == nil {
		return "", false
	}
	return m[1], true
}

// WorkerDefinition is the per-isolate payload the manager serves to the
// dispatcher's WorkerLoader callback. It marshals to workerd's WorkerCode JSON
// shape: { compatibilityDate, compatibilityFlags, mainModule, modules, env }.
type WorkerDefinition struct {
	CompatibilityDate  string                   `json:"compatibilityDate"`
	CompatibilityFlags []string                 `json:"compatibilityFlags,omitempty"`
	MainModule         string                   `json:"mainModule"`
	Modules            map[string]moduleContent `json:"modules"`
	Env                map[string]string        `json:"env,omitempty"`
}

// moduleContent marshals to the WorkerLoader runtime module shape — a single-key
// object keyed by the WorkerLoader JS module kind, e.g. {"js": "<source>"}.
//
// NOTE: the WorkerLoader *runtime* `modules` map keys ("js"/"cjs"/"text"/"data"/
// "json"/"wasm") differ from the *capnp config* Worker.Module union field names
// ("esModule"/"commonJsModule"/...). BuildWorkerdConfig emits the capnp names;
// this path emits the WorkerLoader names. The 796-0 de-risking spike confirmed
// against stock workerd that a module emitted with the capnp "esModule" key is
// rejected by the runtime loader ("must contain exactly one of 'js', 'cjs',
// 'text', 'data', 'json', 'py', or 'wasm'"); the in-tree end-to-end proof is the
// linux acceptance test, not a committed spike artifact.
type moduleContent struct {
	kind computev1alpha1.ModuleType
	body string
}

func (m moduleContent) MarshalJSON() ([]byte, error) {
	key, ok := workerLoaderModuleKey(m.kind)
	if !ok {
		return nil, fmt.Errorf("workerd-host: module kind %q has no WorkerLoader key", m.kind)
	}
	return json.Marshal(map[string]string{key: m.body})
}

// workerLoaderModuleKey maps a compute ModuleType to the WorkerLoader runtime
// module-map key.
func workerLoaderModuleKey(t computev1alpha1.ModuleType) (string, bool) {
	switch t {
	case computev1alpha1.ESModule:
		return "js", true
	case computev1alpha1.CommonJSModule:
		return "cjs", true
	case computev1alpha1.TextModule:
		return "text", true
	case computev1alpha1.JSONModule:
		return "json", true
	case computev1alpha1.DataModule:
		return "data", true
	case computev1alpha1.WasmModule:
		return "wasm", true
	}
	return "", false
}

var errAssetsUnsupportedInDispatcher = errors.New("workerd-host: static assets are not yet supported in the dispatcher WorkerLoader path")

// BuildWorkerDefinition renders the WorkerCode payload for one ServiceRevision.
// source maps each Module.Name to its raw bytes (read from the extracted bundle
// by the manager); BuildWorkerDefinition stays pure and filesystem-free so it is
// table-testable. The first esModule is the entrypoint (mainModule).
// secrets maps binding names (type=secret) to resolved values; see BuildInput.Secrets.
func BuildWorkerDefinition(
	manifest computev1alpha1.BundleManifest,
	cfg computev1alpha1.ServiceConfigSpec,
	source map[string][]byte,
	secrets map[string]string,
) (WorkerDefinition, error) {
	compatDate := manifest.CompatibilityDate
	if cfg.Runtime != nil && cfg.Runtime.CompatibilityDate != "" {
		compatDate = cfg.Runtime.CompatibilityDate
	}
	if compatDate == "" {
		return WorkerDefinition{}, errNoCompatibilityDate
	}
	if manifest.AssetsPrefix != "" {
		return WorkerDefinition{}, errAssetsUnsupportedInDispatcher
	}

	modules, err := orderModules(manifest.Modules)
	if err != nil {
		return WorkerDefinition{}, err
	}

	env, err := buildEnvMap(cfg, secrets)
	if err != nil {
		return WorkerDefinition{}, err
	}

	out := WorkerDefinition{
		CompatibilityDate:  compatDate,
		CompatibilityFlags: unionFlags(manifest.CompatibilityFlags, runtimeFlags(cfg)),
		MainModule:         modules[0].Name,
		Modules:            make(map[string]moduleContent, len(modules)),
		Env:                env,
	}
	for _, m := range modules {
		body, ok := source[m.Name]
		if !ok {
			return WorkerDefinition{}, fmt.Errorf("workerd-host: missing source for module %q", m.Name)
		}
		mc, err := newModuleContent(m.Type, body)
		if err != nil {
			return WorkerDefinition{}, err
		}
		out.Modules[m.Name] = mc
	}
	return out, nil
}

// newModuleContent maps a module's bytes to its WorkerCode representation. The
// text-based kinds carry inline source; binary kinds (data/wasm) would need
// base64 transit plus dispatcher-side decoding and are deferred.
func newModuleContent(t computev1alpha1.ModuleType, body []byte) (moduleContent, error) {
	switch t {
	case computev1alpha1.ESModule, computev1alpha1.CommonJSModule,
		computev1alpha1.TextModule, computev1alpha1.JSONModule:
		return moduleContent{kind: t, body: string(body)}, nil
	case computev1alpha1.DataModule, computev1alpha1.WasmModule:
		return moduleContent{}, fmt.Errorf("workerd-host: binary module type %q is not yet supported in the dispatcher WorkerLoader path", t)
	default:
		return moduleContent{}, fmt.Errorf("workerd-host: unknown module type %q", t)
	}
}

// buildEnvMap materializes env vars and resolved secret bindings into the
// WorkerCode env object. kv/service bindings are not yet supported (APO-874)
// — encountering one is an explicit error, never a silent skip.
func buildEnvMap(cfg computev1alpha1.ServiceConfigSpec, secrets map[string]string) (map[string]string, error) {
	if len(cfg.Env) == 0 && len(cfg.Bindings) == 0 {
		return nil, nil
	}
	env := make(map[string]string, len(cfg.Env)+len(cfg.Bindings))
	for _, e := range cfg.Env {
		env[e.Name] = e.Value
	}
	for i := range cfg.Bindings {
		value, err := secretBindingValue(&cfg.Bindings[i], env, secrets)
		if err != nil {
			return nil, err
		}
		env[cfg.Bindings[i].Name] = value
	}
	return env, nil
}

// secretBindingValue resolves one binding to its env value: only secret
// bindings are supported, the caller must have supplied the resolved value,
// and the name must not collide with a plain env var.
func secretBindingValue(bd *computev1alpha1.Binding, env map[string]string, secrets map[string]string) (string, error) {
	if bd.Type != computev1alpha1.SecretBindingType {
		return "", fmt.Errorf("workerd-host: binding %q of type %q is not supported yet (kv/service bindings are APO-874)", bd.Name, bd.Type)
	}
	if bd.Secret == nil {
		return "", fmt.Errorf("workerd-host: secret binding %q has no secret block", bd.Name)
	}
	if _, dup := env[bd.Name]; dup {
		return "", fmt.Errorf("workerd-host: secret binding %q collides with an env var of the same name", bd.Name)
	}
	value, ok := secrets[bd.Name]
	if !ok {
		return "", fmt.Errorf("workerd-host: secret binding %q has no resolved value (store %q key %q)", bd.Name, bd.Secret.Store, bd.Secret.Key)
	}
	return value, nil
}

type bindingKind string

const (
	bindingText    bindingKind = "text"
	bindingService bindingKind = "service"
)

type binding struct {
	name  string
	kind  bindingKind
	value string
}

// orderModules validates module types and returns the modules with the first
// esModule moved to the front: workerd treats the first module in the list as
// the worker's entrypoint. Relative order of the remaining modules is
// preserved.
func orderModules(in []computev1alpha1.Module) ([]computev1alpha1.Module, error) {
	for _, m := range in {
		if !knownModuleFields[m.Type] {
			return nil, fmt.Errorf("workerd-host: module %q has unknown type %q", m.Name, m.Type)
		}
	}
	entry := -1
	for i, m := range in {
		if m.Type == computev1alpha1.ESModule {
			entry = i
			break
		}
	}
	if entry == -1 {
		return nil, errNoEntrypoint
	}
	out := make([]computev1alpha1.Module, 0, len(in))
	out = append(out, in[entry])
	for i, m := range in {
		if i == entry {
			continue
		}
		out = append(out, m)
	}
	return out, nil
}

// buildBindings materializes env vars and resolved secret bindings into
// workerd text bindings. kv/service bindings are not yet supported (APO-874);
// encountering one is an explicit error rather than a silent skip, so a
// worker is never mis-served after asking for a capability it didn't get.
func buildBindings(cfg computev1alpha1.ServiceConfigSpec, secrets map[string]string) ([]binding, error) {
	var out []binding
	seen := make(map[string]string, len(cfg.Env))
	for _, e := range cfg.Env {
		out = append(out, binding{name: e.Name, kind: bindingText, value: e.Value})
		seen[e.Name] = e.Value
	}
	for i := range cfg.Bindings {
		value, err := secretBindingValue(&cfg.Bindings[i], seen, secrets)
		if err != nil {
			return nil, err
		}
		out = append(out, binding{name: cfg.Bindings[i].Name, kind: bindingText, value: value})
		seen[cfg.Bindings[i].Name] = value
	}
	return out, nil
}

func runtimeFlags(cfg computev1alpha1.ServiceConfigSpec) []string {
	if cfg.Runtime == nil {
		return nil
	}
	return cfg.Runtime.CompatibilityFlags
}

// unionFlags concatenates flag lists preserving first-seen order and dropping
// duplicates and empties.
func unionFlags(lists ...[]string) []string {
	seen := map[string]bool{}
	var out []string
	for _, l := range lists {
		for _, f := range l {
			if f == "" || seen[f] {
				continue
			}
			seen[f] = true
			out = append(out, f)
		}
	}
	return out
}

// capnpStr renders a Go string as a double-quoted capnp text literal.
func capnpStr(s string) string {
	var b strings.Builder
	b.Grow(len(s) + 2)
	b.WriteByte('"')
	for _, r := range s {
		switch r {
		case '"':
			b.WriteString(`\"`)
		case '\\':
			b.WriteString(`\\`)
		case '\n':
			b.WriteString(`\n`)
		case '\r':
			b.WriteString(`\r`)
		case '\t':
			b.WriteString(`\t`)
		default:
			b.WriteRune(r)
		}
	}
	b.WriteByte('"')
	return b.String()
}

// capnpStrList renders a slice of strings as a comma-separated capnp text-list
// body (without the enclosing brackets).
func capnpStrList(ss []string) string {
	parts := make([]string, len(ss))
	for i, s := range ss {
		parts[i] = capnpStr(s)
	}
	return strings.Join(parts, ", ")
}
