// SPDX-License-Identifier: AGPL-3.0-only

package host

import (
	"errors"
	"fmt"
	"strings"

	computev1alpha1 "github.com/apoxy-dev/apoxy/api/compute/v1alpha1"
)

// Internal workerd identifiers used in the emitted config. These are
// platform-internal contracts, not user-visible.
const (
	// workerServiceName is the workerd service name for the worker.
	workerServiceName = "main"
	// assetsServiceName is the workerd disk service name for static assets.
	assetsServiceName = "assets"
	// assetsBindingName is the env binding the worker uses to reach assets
	// (env.ASSETS.fetch(...)).
	assetsBindingName = "ASSETS"
	// httpSocketName is the workerd socket name for the http socket.
	httpSocketName = "http"
)

// knownModuleFields is the set of workerd Worker.Module union fields. The
// compute ModuleType constants are authored to equal these field names 1:1
// (see api/compute/v1alpha1.ModuleType — "mirrors workerd's module union"),
// so the type string is emitted directly as the capnp field name.
var knownModuleFields = map[computev1alpha1.ModuleType]bool{
	computev1alpha1.ESModule:       true,
	computev1alpha1.CommonJSModule: true,
	computev1alpha1.TextModule:     true,
	computev1alpha1.DataModule:     true,
	computev1alpha1.JSONModule:     true,
	computev1alpha1.WasmModule:     true,
}

var (
	errNoCompatibilityDate = errors.New("workerd-host: compatibilityDate is required (workerd refuses to start without it)")
	errNoEntrypoint        = errors.New("workerd-host: bundle has no esModule entrypoint module")
)

// BuildInput is the input to BuildWorkerdConfig.
type BuildInput struct {
	// Manifest is the bundle's BundleManifest (modules + compat + assets).
	Manifest computev1alpha1.BundleManifest
	// Config is the revision's serving config (runtime overrides, bindings, env).
	Config computev1alpha1.ServiceConfigSpec
	// Socket is the listening socket workerd binds.
	Socket SocketSpec
	// AssetsDir is the in-jail absolute path the assets layer extracted to.
	// Used only when Manifest.AssetsPrefix is set.
	AssetsDir string
}

// BuildWorkerdConfig renders the textual capnp config that `workerd serve`
// consumes. It is a pure, deterministic function: identical input yields
// byte-identical output. Module `embed` paths are emitted relative to the
// config file, which the host co-locates with the extracted modules layer so
// each path is just Module.Path.
func BuildWorkerdConfig(in BuildInput) (string, error) {
	switch in.Socket.Kind {
	case HTTPSocket:
		// ok
	case FilterSocket:
		return "", errFilterSocketUnsupported
	default:
		return "", fmt.Errorf("workerd-host: unsupported socket kind %d", in.Socket.Kind)
	}

	compatDate := in.Manifest.CompatibilityDate
	if in.Config.Runtime != nil && in.Config.Runtime.CompatibilityDate != "" {
		compatDate = in.Config.Runtime.CompatibilityDate
	}
	if compatDate == "" {
		return "", errNoCompatibilityDate
	}

	modules, err := orderModules(in.Manifest.Modules)
	if err != nil {
		return "", err
	}

	bindings, err := buildBindings(in.Config)
	if err != nil {
		return "", err
	}

	hasAssets := in.Manifest.AssetsPrefix != ""
	if hasAssets {
		bindings = append(bindings, binding{name: assetsBindingName, kind: bindingService, value: assetsServiceName})
	}

	flags := unionFlags(in.Manifest.CompatibilityFlags, runtimeFlags(in.Config))

	var b strings.Builder
	b.WriteString("# Generated by apoxy workerd-host. DO NOT EDIT.\n")
	b.WriteString(`using Workerd = import "/workerd/workerd.capnp";` + "\n\n")

	// Top-level Config: services + sockets.
	b.WriteString("const config :Workerd.Config = (\n")
	b.WriteString("  services = [\n")
	fmt.Fprintf(&b, "    (name = %s, worker = .mainWorker),\n", capnpStr(workerServiceName))
	if hasAssets {
		fmt.Fprintf(&b, "    (name = %s, disk = (path = %s, writable = false)),\n",
			capnpStr(assetsServiceName), capnpStr(in.AssetsDir))
	}
	b.WriteString("  ],\n")
	b.WriteString("  sockets = [\n")
	fmt.Fprintf(&b, "    (name = %s, address = %s, http = (), service = %s),\n",
		capnpStr(httpSocketName), capnpStr(in.Socket.Addr), capnpStr(workerServiceName))
	b.WriteString("  ],\n")
	b.WriteString(");\n\n")

	// The worker itself.
	b.WriteString("const mainWorker :Workerd.Worker = (\n")
	fmt.Fprintf(&b, "  compatibilityDate = %s,\n", capnpStr(compatDate))
	if len(flags) > 0 {
		fmt.Fprintf(&b, "  compatibilityFlags = [%s],\n", capnpStrList(flags))
	}
	b.WriteString("  modules = [\n")
	for _, m := range modules {
		fmt.Fprintf(&b, "    (name = %s, %s = embed %s),\n",
			capnpStr(m.Name), string(m.Type), capnpStr(m.Path))
	}
	b.WriteString("  ],\n")
	if len(bindings) > 0 {
		b.WriteString("  bindings = [\n")
		for _, bd := range bindings {
			switch bd.kind {
			case bindingText:
				fmt.Fprintf(&b, "    (name = %s, text = %s),\n", capnpStr(bd.name), capnpStr(bd.value))
			case bindingService:
				fmt.Fprintf(&b, "    (name = %s, service = %s),\n", capnpStr(bd.name), capnpStr(bd.value))
			default:
				return "", fmt.Errorf("workerd-host: unknown binding kind %q", bd.kind)
			}
		}
		b.WriteString("  ],\n")
	}
	b.WriteString(");\n")

	return b.String(), nil
}

type bindingKind string

const (
	bindingText    bindingKind = "text"
	bindingService bindingKind = "service"
)

type binding struct {
	name  string
	kind  bindingKind
	value string
}

// orderModules validates module types and returns the modules with the first
// esModule moved to the front: workerd treats the first module in the list as
// the worker's entrypoint. Relative order of the remaining modules is
// preserved.
func orderModules(in []computev1alpha1.Module) ([]computev1alpha1.Module, error) {
	for _, m := range in {
		if !knownModuleFields[m.Type] {
			return nil, fmt.Errorf("workerd-host: module %q has unknown type %q", m.Name, m.Type)
		}
	}
	entry := -1
	for i, m := range in {
		if m.Type == computev1alpha1.ESModule {
			entry = i
			break
		}
	}
	if entry == -1 {
		return nil, errNoEntrypoint
	}
	out := make([]computev1alpha1.Module, 0, len(in))
	out = append(out, in[entry])
	for i, m := range in {
		if i == entry {
			continue
		}
		out = append(out, m)
	}
	return out, nil
}

// buildBindings materializes env vars into workerd text bindings. Typed
// bindings (secret/kv/service) require external resolution (e.g. fetching the
// referenced Secret) and are deferred to APO-627; encountering one is an
// explicit error rather than a silent skip, so M1 never mis-serves a worker
// that asked for a capability it didn't get.
func buildBindings(cfg computev1alpha1.ServiceConfigSpec) ([]binding, error) {
	var out []binding
	for _, e := range cfg.Env {
		out = append(out, binding{name: e.Name, kind: bindingText, value: e.Value})
	}
	for _, bd := range cfg.Bindings {
		return nil, fmt.Errorf("workerd-host: binding %q of type %q is not supported in M1 (deferred to APO-627)", bd.Name, bd.Type)
	}
	return out, nil
}

func runtimeFlags(cfg computev1alpha1.ServiceConfigSpec) []string {
	if cfg.Runtime == nil {
		return nil
	}
	return cfg.Runtime.CompatibilityFlags
}

// unionFlags concatenates flag lists preserving first-seen order and dropping
// duplicates and empties.
func unionFlags(lists ...[]string) []string {
	seen := map[string]bool{}
	var out []string
	for _, l := range lists {
		for _, f := range l {
			if f == "" || seen[f] {
				continue
			}
			seen[f] = true
			out = append(out, f)
		}
	}
	return out
}

// capnpStr renders a Go string as a double-quoted capnp text literal.
func capnpStr(s string) string {
	var b strings.Builder
	b.Grow(len(s) + 2)
	b.WriteByte('"')
	for _, r := range s {
		switch r {
		case '"':
			b.WriteString(`\"`)
		case '\\':
			b.WriteString(`\\`)
		case '\n':
			b.WriteString(`\n`)
		case '\r':
			b.WriteString(`\r`)
		case '\t':
			b.WriteString(`\t`)
		default:
			b.WriteRune(r)
		}
	}
	b.WriteByte('"')
	return b.String()
}

// capnpStrList renders a slice of strings as a comma-separated capnp text-list
// body (without the enclosing brackets).
func capnpStrList(ss []string) string {
	parts := make([]string, len(ss))
	for i, s := range ss {
		parts[i] = capnpStr(s)
	}
	return strings.Join(parts, ", ")
}
