/*
Copyright 2026 Apoxy, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	vpcv1alpha1 "github.com/apoxy-dev/apoxy/api/vpc/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// RelayLister helps list Relays.
// All objects returned here must be treated as read-only.
type RelayLister interface {
	// List lists all Relays in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*vpcv1alpha1.Relay, err error)
	// Get retrieves the Relay from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*vpcv1alpha1.Relay, error)
	RelayListerExpansion
}

// relayLister implements the RelayLister interface.
type relayLister struct {
	listers.ResourceIndexer[*vpcv1alpha1.Relay]
}

// NewRelayLister returns a new RelayLister.
func NewRelayLister(indexer cache.Indexer) RelayLister {
	return &relayLister{listers.New[*vpcv1alpha1.Relay](indexer, vpcv1alpha1.Resource("relay"))}
}
