/*
Copyright 2026 Apoxy, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	vpcv1alpha1 "github.com/apoxy-dev/apoxy/api/vpc/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// VPCNetworkLister helps list VPCNetworks.
// All objects returned here must be treated as read-only.
type VPCNetworkLister interface {
	// List lists all VPCNetworks in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*vpcv1alpha1.VPCNetwork, err error)
	// Get retrieves the VPCNetwork from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*vpcv1alpha1.VPCNetwork, error)
	VPCNetworkListerExpansion
}

// vPCNetworkLister implements the VPCNetworkLister interface.
type vPCNetworkLister struct {
	listers.ResourceIndexer[*vpcv1alpha1.VPCNetwork]
}

// NewVPCNetworkLister returns a new VPCNetworkLister.
func NewVPCNetworkLister(indexer cache.Indexer) VPCNetworkLister {
	return &vPCNetworkLister{listers.New[*vpcv1alpha1.VPCNetwork](indexer, vpcv1alpha1.Resource("vpcnetwork"))}
}
