// SPDX-License-Identifier: AGPL-3.0-only
//
// EgressConfig is the worker-side sink of the workerd egress config plane
// (APO-723). The backplane's egress reconciler (APO-726) compiles egress
// routing/policy per compute Service and pushes it here over a per-tenant
// localhost listener (a filesystem-permissioned unix domain socket); the
// manager fans it out to the sandbox EgressController live setters.
//
// This gRPC drives the WORKER bridge's setters only, never the Sentry: there
// is no general live urpc into the running sandbox. Applies are idempotent and
// last-writer-wins, ordered by generation.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.3
// source: egress.proto

package workerdv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BackendListener mirrors the sandbox.BackendListener seam type: one
// EgressGateway listener the sandbox may dial.
type BackendListener struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Name mirrors the EgressListener name from the CRD; used for logs and for
	// EgressRoute parentRef.sectionName matching.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Addr is the host:port the sandbox dials. Empty means "listener exists but
	// its data plane isn't ready yet" — the dialer skips it.
	Addr string `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	// Shape is the on-the-wire protocol selector ("tls-terminate",
	// "tls-passthrough", "tcp", "http", "https").
	Shape string `protobuf:"bytes,3,opt,name=shape,proto3" json:"shape,omitempty"`
	// MatchPort, when non-zero, narrows this listener to the sandbox's
	// destination port. Zero = catch-all for this shape.
	MatchPort int32 `protobuf:"varint,4,opt,name=match_port,json=matchPort,proto3" json:"match_port,omitempty"`
	// Priority is the precomputed shape rank used as a tiebreaker when multiple
	// listeners match the same dst port. Higher wins.
	Priority int32 `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
}

func (x *BackendListener) Reset() {
	*x = BackendListener{}
	mi := &file_egress_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackendListener) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendListener) ProtoMessage() {}

func (x *BackendListener) ProtoReflect() protoreflect.Message {
	mi := &file_egress_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendListener.ProtoReflect.Descriptor instead.
func (*BackendListener) Descriptor() ([]byte, []int) {
	return file_egress_proto_rawDescGZIP(), []int{0}
}

func (x *BackendListener) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BackendListener) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *BackendListener) GetShape() string {
	if x != nil {
		return x.Shape
	}
	return ""
}

func (x *BackendListener) GetMatchPort() int32 {
	if x != nil {
		return x.MatchPort
	}
	return 0
}

func (x *BackendListener) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

// EgressPolicy is one Service's egress authorization plane: the EgressGateway
// defaultPolicy paired with the allow rules compiled from the EgressRoutes
// attached to that gateway. A destination matched by any rule is allowed;
// otherwise default_deny decides (mirroring clrk's SandboxPolicy.Allow).
type EgressPolicy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// DefaultDeny denies destinations not matched by any rule. False (with no
	// rules) is allow-all.
	DefaultDeny bool `protobuf:"varint,1,opt,name=default_deny,json=defaultDeny,proto3" json:"default_deny,omitempty"`
	// Rules are the compiled per-destination allow rules. Dimensions within a
	// rule are ANDed; rules are ORed (each rule is one compiled
	// EgressRouteMatch).
	Rules []*EgressRule `protobuf:"bytes,2,rep,name=rules,proto3" json:"rules,omitempty"`
}

func (x *EgressPolicy) Reset() {
	*x = EgressPolicy{}
	mi := &file_egress_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EgressPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EgressPolicy) ProtoMessage() {}

func (x *EgressPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_egress_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EgressPolicy.ProtoReflect.Descriptor instead.
func (*EgressPolicy) Descriptor() ([]byte, []int) {
	return file_egress_proto_rawDescGZIP(), []int{1}
}

func (x *EgressPolicy) GetDefaultDeny() bool {
	if x != nil {
		return x.DefaultDeny
	}
	return false
}

func (x *EgressPolicy) GetRules() []*EgressRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

// EgressRule is one compiled EgressRouteMatch: an AND of destination
// dimensions (each present dimension must match; an absent dimension matches
// anything).
type EgressRule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// DestinationCIDRs match the destination IP. Single IPs are /32 or /128.
	DestinationCidrs []string `protobuf:"bytes,1,rep,name=destination_cidrs,json=destinationCidrs,proto3" json:"destination_cidrs,omitempty"`
	// DestinationHostnames match the DNS-bound destination name; exact or
	// single-label wildcard ("*.example.com").
	DestinationHostnames []string `protobuf:"bytes,2,rep,name=destination_hostnames,json=destinationHostnames,proto3" json:"destination_hostnames,omitempty"`
	// Ports match the destination port. Single ports have start == end.
	Ports []*PortRange `protobuf:"bytes,3,rep,name=ports,proto3" json:"ports,omitempty"`
	// Protocol is the L4 protocol ("TCP"); empty matches any. UDP is rejected
	// at admission and never compiled.
	Protocol string `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
	// Listeners are the BackendListener names this rule routes via, from the
	// route's parentRef.sectionName. Empty = all of the gateway's listeners.
	Listeners []string `protobuf:"bytes,5,rep,name=listeners,proto3" json:"listeners,omitempty"`
}

func (x *EgressRule) Reset() {
	*x = EgressRule{}
	mi := &file_egress_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EgressRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EgressRule) ProtoMessage() {}

func (x *EgressRule) ProtoReflect() protoreflect.Message {
	mi := &file_egress_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EgressRule.ProtoReflect.Descriptor instead.
func (*EgressRule) Descriptor() ([]byte, []int) {
	return file_egress_proto_rawDescGZIP(), []int{2}
}

func (x *EgressRule) GetDestinationCidrs() []string {
	if x != nil {
		return x.DestinationCidrs
	}
	return nil
}

func (x *EgressRule) GetDestinationHostnames() []string {
	if x != nil {
		return x.DestinationHostnames
	}
	return nil
}

func (x *EgressRule) GetPorts() []*PortRange {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *EgressRule) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *EgressRule) GetListeners() []string {
	if x != nil {
		return x.Listeners
	}
	return nil
}

// PortRange is an inclusive destination port range.
type PortRange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Start int32 `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End   int32 `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
}

func (x *PortRange) Reset() {
	*x = PortRange{}
	mi := &file_egress_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortRange) ProtoMessage() {}

func (x *PortRange) ProtoReflect() protoreflect.Message {
	mi := &file_egress_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortRange.ProtoReflect.Descriptor instead.
func (*PortRange) Descriptor() ([]byte, []int) {
	return file_egress_proto_rawDescGZIP(), []int{3}
}

func (x *PortRange) GetStart() int32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *PortRange) GetEnd() int32 {
	if x != nil {
		return x.End
	}
	return 0
}

// ServiceEgressConfig is one compute Service's compiled egress plane within
// the resident: the gateway listeners its egress may dial and its policy. A
// resident hosts every Service of its project, and Services select egress
// gateways independently (spec.template.spec.egress.gatewayRef), so egress
// state is keyed per Service — this is a deliberate divergence from clrk,
// where one sandbox hosts exactly one agent workload.
type ServiceEgressConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Service is the compute Service name this plane belongs to.
	Service string `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	// Backends replaces the Service's dialable EgressGateway listener set.
	Backends []*BackendListener `protobuf:"bytes,2,rep,name=backends,proto3" json:"backends,omitempty"`
	// Policy replaces the Service's egress authorization plane. Absent means
	// allow-all (no enforcement) — the implicit built-in "default" gateway.
	Policy *EgressPolicy `protobuf:"bytes,3,opt,name=policy,proto3" json:"policy,omitempty"`
}

func (x *ServiceEgressConfig) Reset() {
	*x = ServiceEgressConfig{}
	mi := &file_egress_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceEgressConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceEgressConfig) ProtoMessage() {}

func (x *ServiceEgressConfig) ProtoReflect() protoreflect.Message {
	mi := &file_egress_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceEgressConfig.ProtoReflect.Descriptor instead.
func (*ServiceEgressConfig) Descriptor() ([]byte, []int) {
	return file_egress_proto_rawDescGZIP(), []int{4}
}

func (x *ServiceEgressConfig) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *ServiceEgressConfig) GetBackends() []*BackendListener {
	if x != nil {
		return x.Backends
	}
	return nil
}

func (x *ServiceEgressConfig) GetPolicy() *EgressPolicy {
	if x != nil {
		return x.Policy
	}
	return nil
}

type ApplyEgressRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// SandboxID identifies the target sandbox. It must belong to the tenant
	// whose socket this request arrived on; a foreign id is rejected.
	SandboxId string `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	// InvocationID is stamped on egress connections (PROXY v2 TLV) dialed
	// through this sandbox, for attribution.
	InvocationId string `protobuf:"bytes,4,opt,name=invocation_id,json=invocationId,proto3" json:"invocation_id,omitempty"`
	// Generation orders applies: the reconciler's monotonically increasing
	// config generation. A stale generation is not applied.
	Generation uint64 `protobuf:"varint,5,opt,name=generation,proto3" json:"generation,omitempty"`
	// Services is the full desired set of per-Service egress planes for the
	// resident; it replaces the prior set atomically.
	Services []*ServiceEgressConfig `protobuf:"bytes,6,rep,name=services,proto3" json:"services,omitempty"`
}

func (x *ApplyEgressRequest) Reset() {
	*x = ApplyEgressRequest{}
	mi := &file_egress_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyEgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyEgressRequest) ProtoMessage() {}

func (x *ApplyEgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_egress_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyEgressRequest.ProtoReflect.Descriptor instead.
func (*ApplyEgressRequest) Descriptor() ([]byte, []int) {
	return file_egress_proto_rawDescGZIP(), []int{5}
}

func (x *ApplyEgressRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *ApplyEgressRequest) GetInvocationId() string {
	if x != nil {
		return x.InvocationId
	}
	return ""
}

func (x *ApplyEgressRequest) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *ApplyEgressRequest) GetServices() []*ServiceEgressConfig {
	if x != nil {
		return x.Services
	}
	return nil
}

type ApplyEgressResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// AppliedGeneration is the generation now in effect for the sandbox — the
	// request's generation if it was applied, or the newer retained one if the
	// request was stale.
	AppliedGeneration uint64 `protobuf:"varint,1,opt,name=applied_generation,json=appliedGeneration,proto3" json:"applied_generation,omitempty"`
}

func (x *ApplyEgressResponse) Reset() {
	*x = ApplyEgressResponse{}
	mi := &file_egress_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyEgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyEgressResponse) ProtoMessage() {}

func (x *ApplyEgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_egress_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyEgressResponse.ProtoReflect.Descriptor instead.
func (*ApplyEgressResponse) Descriptor() ([]byte, []int) {
	return file_egress_proto_rawDescGZIP(), []int{6}
}

func (x *ApplyEgressResponse) GetAppliedGeneration() uint64 {
	if x != nil {
		return x.AppliedGeneration
	}
	return 0
}

var File_egress_proto protoreflect.FileDescriptor

var file_egress_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x65, 0x67, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10,
	0x61, 0x70, 0x6f, 0x78, 0x79, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x64, 0x2e, 0x76, 0x31,
	0x22, 0x8a, 0x01, 0x0a, 0x0f, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x4c, 0x69, 0x73, 0x74,
	0x65, 0x6e, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x68, 0x61, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x68, 0x61,
	0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x70, 0x6f, 0x72, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x50, 0x6f, 0x72,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x22, 0x65, 0x0a,
	0x0c, 0x45, 0x67, 0x72, 0x65, 0x73, 0x73, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x12, 0x21, 0x0a,
	0x0c, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x64, 0x65, 0x6e, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0b, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x44, 0x65, 0x6e, 0x79,
	0x12, 0x32, 0x0a, 0x05, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1c, 0x2e, 0x61, 0x70, 0x6f, 0x78, 0x79, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x64, 0x2e,
	0x76, 0x31, 0x2e, 0x45, 0x67, 0x72, 0x65, 0x73, 0x73, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x05, 0x72,
	0x75, 0x6c, 0x65, 0x73, 0x22, 0xe1, 0x01, 0x0a, 0x0a, 0x45, 0x67, 0x72, 0x65, 0x73, 0x73, 0x52,
	0x75, 0x6c, 0x65, 0x12, 0x2b, 0x0a, 0x11, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x63, 0x69, 0x64, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x10,
	0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x69, 0x64, 0x72, 0x73,
	0x12, 0x33, 0x0a, 0x15, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x14, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x6f, 0x73, 0x74,
	0x6e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x31, 0x0a, 0x05, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x61, 0x70, 0x6f, 0x78, 0x79, 0x2e, 0x77, 0x6f, 0x72,
	0x6b, 0x65, 0x72, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x72, 0x74, 0x52, 0x61, 0x6e, 0x67,
	0x65, 0x52, 0x05, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72,
	0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65,
	0x72, 0x73, 0x4a, 0x04, 0x08, 0x06, 0x10, 0x07, 0x22, 0x33, 0x0a, 0x09, 0x50, 0x6f, 0x72, 0x74,
	0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x65,
	0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x22, 0xa6, 0x01,
	0x0a, 0x13, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x45, 0x67, 0x72, 0x65, 0x73, 0x73, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x3d, 0x0a, 0x08, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x21, 0x2e, 0x61, 0x70, 0x6f, 0x78, 0x79, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72,
	0x64, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x4c, 0x69, 0x73, 0x74,
	0x65, 0x6e, 0x65, 0x72, 0x52, 0x08, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x73, 0x12, 0x36,
	0x0a, 0x06, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e,
	0x2e, 0x61, 0x70, 0x6f, 0x78, 0x79, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x64, 0x2e, 0x76,
	0x31, 0x2e, 0x45, 0x67, 0x72, 0x65, 0x73, 0x73, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x52, 0x06,
	0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x22, 0xc7, 0x01, 0x0a, 0x12, 0x41, 0x70, 0x70, 0x6c, 0x79,
	0x45, 0x67, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d,
	0x69, 0x6e, 0x76, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x69, 0x6e, 0x76, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x41, 0x0a, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18, 0x06, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x61, 0x70, 0x6f, 0x78, 0x79, 0x2e, 0x77, 0x6f, 0x72, 0x6b,
	0x65, 0x72, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x45, 0x67,
	0x72, 0x65, 0x73, 0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x4a, 0x04, 0x08, 0x02, 0x10, 0x03, 0x4a, 0x04, 0x08, 0x03, 0x10, 0x04,
	0x22, 0x44, 0x0a, 0x13, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x45, 0x67, 0x72, 0x65, 0x73, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x12, 0x61, 0x70, 0x70, 0x6c, 0x69,
	0x65, 0x64, 0x5f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x11, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x64, 0x47, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0x6a, 0x0a, 0x0c, 0x45, 0x67, 0x72, 0x65, 0x73, 0x73,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x5a, 0x0a, 0x0b, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x45,
	0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x24, 0x2e, 0x61, 0x70, 0x6f, 0x78, 0x79, 0x2e, 0x77, 0x6f,
	0x72, 0x6b, 0x65, 0x72, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x45, 0x67,
	0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x61, 0x70,
	0x6f, 0x78, 0x79, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x41,
	0x70, 0x70, 0x6c, 0x79, 0x45, 0x67, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x61, 0x70, 0x6f, 0x78, 0x79, 0x2d, 0x64, 0x65, 0x76, 0x2f, 0x61, 0x70, 0x6f, 0x78, 0x79,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x64, 0x2f, 0x76, 0x31, 0x3b,
	0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x64, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_egress_proto_rawDescOnce sync.Once
	file_egress_proto_rawDescData = file_egress_proto_rawDesc
)

func file_egress_proto_rawDescGZIP() []byte {
	file_egress_proto_rawDescOnce.Do(func() {
		file_egress_proto_rawDescData = protoimpl.X.CompressGZIP(file_egress_proto_rawDescData)
	})
	return file_egress_proto_rawDescData
}

var file_egress_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_egress_proto_goTypes = []any{
	(*BackendListener)(nil),     // 0: apoxy.workerd.v1.BackendListener
	(*EgressPolicy)(nil),        // 1: apoxy.workerd.v1.EgressPolicy
	(*EgressRule)(nil),          // 2: apoxy.workerd.v1.EgressRule
	(*PortRange)(nil),           // 3: apoxy.workerd.v1.PortRange
	(*ServiceEgressConfig)(nil), // 4: apoxy.workerd.v1.ServiceEgressConfig
	(*ApplyEgressRequest)(nil),  // 5: apoxy.workerd.v1.ApplyEgressRequest
	(*ApplyEgressResponse)(nil), // 6: apoxy.workerd.v1.ApplyEgressResponse
}
var file_egress_proto_depIdxs = []int32{
	2, // 0: apoxy.workerd.v1.EgressPolicy.rules:type_name -> apoxy.workerd.v1.EgressRule
	3, // 1: apoxy.workerd.v1.EgressRule.ports:type_name -> apoxy.workerd.v1.PortRange
	0, // 2: apoxy.workerd.v1.ServiceEgressConfig.backends:type_name -> apoxy.workerd.v1.BackendListener
	1, // 3: apoxy.workerd.v1.ServiceEgressConfig.policy:type_name -> apoxy.workerd.v1.EgressPolicy
	4, // 4: apoxy.workerd.v1.ApplyEgressRequest.services:type_name -> apoxy.workerd.v1.ServiceEgressConfig
	5, // 5: apoxy.workerd.v1.EgressConfig.ApplyEgress:input_type -> apoxy.workerd.v1.ApplyEgressRequest
	6, // 6: apoxy.workerd.v1.EgressConfig.ApplyEgress:output_type -> apoxy.workerd.v1.ApplyEgressResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_egress_proto_init() }
func file_egress_proto_init() {
	if File_egress_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_egress_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_egress_proto_goTypes,
		DependencyIndexes: file_egress_proto_depIdxs,
		MessageInfos:      file_egress_proto_msgTypes,
	}.Build()
	File_egress_proto = out.File
	file_egress_proto_rawDesc = nil
	file_egress_proto_goTypes = nil
	file_egress_proto_depIdxs = nil
}
