// SPDX-License-Identifier: AGPL-3.0-only
//
// DNSConfig is the worker-side sink of the workerd VPC name plane: the
// manager's per-project infra watch compiles the bindings the project's
// workers may resolve and reach (tunnel endpoints today, VPC-bound Services
// later) and pushes them here over the same per-tenant unix domain socket
// the egress config plane uses. The resident serves the pushed state from
// its own DNS listener (the abstract unixgram socket sealed into the
// sandbox's InitStr) and derives the egress SSRF carve-out from the
// bindings' reachable prefixes.
//
// Like EgressConfig, this drives host-resident state only, never the Sentry:
// the Sentry's :53 forwarder is pointed at the resident's listener once at
// boot and needs no live channel. Applies are idempotent and
// last-writer-wins, ordered by generation.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.3
// source: vpcdns.proto

package workerdv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Binding is one name bound into the project VPC — a tunnel endpoint, a
// VPC-bound Service, or any future object exposing a name to workers.
type Binding struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Fqdn is the name this binding answers for, authoritatively (no trailing
	// dot, e.g. "my-tunnel.tun.apoxy.net").
	Fqdn string `protobuf:"bytes,1,opt,name=fqdn,proto3" json:"fqdn,omitempty"`
	// Addrs are the addresses the name resolves to (answered as A or AAAA by
	// address family; VPC overlay ULAs today).
	Addrs []string `protobuf:"bytes,2,rep,name=addrs,proto3" json:"addrs,omitempty"`
	// DelegateSubdomains forwards sub-names (x.<fqdn>) to a resolver at this
	// binding's addrs instead of answering locally. Tunnel endpoints set this
	// (recursive tunnel resolution); Services won't.
	DelegateSubdomains bool `protobuf:"varint,3,opt,name=delegate_subdomains,json=delegateSubdomains,proto3" json:"delegate_subdomains,omitempty"`
	// Ttl for answers in seconds; 0 = resolver default.
	Ttl uint32 `protobuf:"varint,4,opt,name=ttl,proto3" json:"ttl,omitempty"`
	// ReachableCidrs are carved out of the egress SSRF backstop for this
	// binding — explicit rather than derived from addrs, so a binding can
	// expose a wider window (a tunnel endpoint's whole /96) or none at all (a
	// Service resolving to a public IP contributes no carve-out).
	ReachableCidrs []string `protobuf:"bytes,5,rep,name=reachable_cidrs,json=reachableCidrs,proto3" json:"reachable_cidrs,omitempty"`
}

func (x *Binding) Reset() {
	*x = Binding{}
	mi := &file_vpcdns_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Binding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Binding) ProtoMessage() {}

func (x *Binding) ProtoReflect() protoreflect.Message {
	mi := &file_vpcdns_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Binding.ProtoReflect.Descriptor instead.
func (*Binding) Descriptor() ([]byte, []int) {
	return file_vpcdns_proto_rawDescGZIP(), []int{0}
}

func (x *Binding) GetFqdn() string {
	if x != nil {
		return x.Fqdn
	}
	return ""
}

func (x *Binding) GetAddrs() []string {
	if x != nil {
		return x.Addrs
	}
	return nil
}

func (x *Binding) GetDelegateSubdomains() bool {
	if x != nil {
		return x.DelegateSubdomains
	}
	return false
}

func (x *Binding) GetTtl() uint32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *Binding) GetReachableCidrs() []string {
	if x != nil {
		return x.ReachableCidrs
	}
	return nil
}

type ApplyDNSRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// SandboxID identifies the target sandbox. It must belong to the tenant
	// whose socket this request arrived on; a foreign id is rejected.
	SandboxId string `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	// Generation orders applies: the pusher's monotonically increasing config
	// generation. A stale generation is not applied.
	Generation uint64 `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
	// AuthoritativeZones get an authoritative NXDOMAIN for unbound names
	// within them ("tun.apoxy.net" today); names outside every zone fall
	// through to the resolver's upstream chain.
	AuthoritativeZones []string `protobuf:"bytes,3,rep,name=authoritative_zones,json=authoritativeZones,proto3" json:"authoritative_zones,omitempty"`
	// Bindings is the full desired binding set for the resident; it replaces
	// the prior set atomically.
	Bindings []*Binding `protobuf:"bytes,4,rep,name=bindings,proto3" json:"bindings,omitempty"`
}

func (x *ApplyDNSRequest) Reset() {
	*x = ApplyDNSRequest{}
	mi := &file_vpcdns_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyDNSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyDNSRequest) ProtoMessage() {}

func (x *ApplyDNSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vpcdns_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyDNSRequest.ProtoReflect.Descriptor instead.
func (*ApplyDNSRequest) Descriptor() ([]byte, []int) {
	return file_vpcdns_proto_rawDescGZIP(), []int{1}
}

func (x *ApplyDNSRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *ApplyDNSRequest) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *ApplyDNSRequest) GetAuthoritativeZones() []string {
	if x != nil {
		return x.AuthoritativeZones
	}
	return nil
}

func (x *ApplyDNSRequest) GetBindings() []*Binding {
	if x != nil {
		return x.Bindings
	}
	return nil
}

type ApplyDNSResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// AppliedGeneration is the generation now in effect for the sandbox — the
	// request's generation if it was applied, or the newer retained one if the
	// request was stale.
	AppliedGeneration uint64 `protobuf:"varint,1,opt,name=applied_generation,json=appliedGeneration,proto3" json:"applied_generation,omitempty"`
}

func (x *ApplyDNSResponse) Reset() {
	*x = ApplyDNSResponse{}
	mi := &file_vpcdns_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyDNSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyDNSResponse) ProtoMessage() {}

func (x *ApplyDNSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vpcdns_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyDNSResponse.ProtoReflect.Descriptor instead.
func (*ApplyDNSResponse) Descriptor() ([]byte, []int) {
	return file_vpcdns_proto_rawDescGZIP(), []int{2}
}

func (x *ApplyDNSResponse) GetAppliedGeneration() uint64 {
	if x != nil {
		return x.AppliedGeneration
	}
	return 0
}

var File_vpcdns_proto protoreflect.FileDescriptor

var file_vpcdns_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x76, 0x70, 0x63, 0x64, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10,
	0x61, 0x70, 0x6f, 0x78, 0x79, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x64, 0x2e, 0x76, 0x31,
	0x22, 0x9f, 0x01, 0x0a, 0x07, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x12, 0x0a, 0x04,
	0x66, 0x71, 0x64, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x71, 0x64, 0x6e,
	0x12, 0x14, 0x0a, 0x05, 0x61, 0x64, 0x64, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x05, 0x61, 0x64, 0x64, 0x72, 0x73, 0x12, 0x2f, 0x0a, 0x13, 0x64, 0x65, 0x6c, 0x65, 0x67, 0x61,
	0x74, 0x65, 0x5f, 0x73, 0x75, 0x62, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x12, 0x64, 0x65, 0x6c, 0x65, 0x67, 0x61, 0x74, 0x65, 0x53, 0x75, 0x62,
	0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x74, 0x6c, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x74, 0x74, 0x6c, 0x12, 0x27, 0x0a, 0x0f, 0x72, 0x65, 0x61,
	0x63, 0x68, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x63, 0x69, 0x64, 0x72, 0x73, 0x18, 0x05, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0e, 0x72, 0x65, 0x61, 0x63, 0x68, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x69, 0x64,
	0x72, 0x73, 0x22, 0xb8, 0x01, 0x0a, 0x0f, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x44, 0x4e, 0x53, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f,
	0x78, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x61, 0x6e, 0x64,
	0x62, 0x6f, 0x78, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x67, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2f, 0x0a, 0x13, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69,
	0x74, 0x61, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x7a, 0x6f, 0x6e, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x12, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x74, 0x61, 0x74, 0x69, 0x76,
	0x65, 0x5a, 0x6f, 0x6e, 0x65, 0x73, 0x12, 0x35, 0x0a, 0x08, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e,
	0x67, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x61, 0x70, 0x6f, 0x78, 0x79,
	0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x69, 0x6e, 0x64,
	0x69, 0x6e, 0x67, 0x52, 0x08, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x22, 0x41, 0x0a,
	0x10, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x44, 0x4e, 0x53, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2d, 0x0a, 0x12, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x64, 0x5f, 0x67, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x11, 0x61,
	0x70, 0x70, 0x6c, 0x69, 0x65, 0x64, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x32, 0x5e, 0x0a, 0x09, 0x44, 0x4e, 0x53, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x51, 0x0a,
	0x08, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x44, 0x4e, 0x53, 0x12, 0x21, 0x2e, 0x61, 0x70, 0x6f, 0x78,
	0x79, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x70, 0x70,
	0x6c, 0x79, 0x44, 0x4e, 0x53, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x61,
	0x70, 0x6f, 0x78, 0x79, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x64, 0x2e, 0x76, 0x31, 0x2e,
	0x41, 0x70, 0x70, 0x6c, 0x79, 0x44, 0x4e, 0x53, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61,
	0x70, 0x6f, 0x78, 0x79, 0x2d, 0x64, 0x65, 0x76, 0x2f, 0x61, 0x70, 0x6f, 0x78, 0x79, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x64, 0x2f, 0x76, 0x31, 0x3b, 0x77, 0x6f,
	0x72, 0x6b, 0x65, 0x72, 0x64, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_vpcdns_proto_rawDescOnce sync.Once
	file_vpcdns_proto_rawDescData = file_vpcdns_proto_rawDesc
)

func file_vpcdns_proto_rawDescGZIP() []byte {
	file_vpcdns_proto_rawDescOnce.Do(func() {
		file_vpcdns_proto_rawDescData = protoimpl.X.CompressGZIP(file_vpcdns_proto_rawDescData)
	})
	return file_vpcdns_proto_rawDescData
}

var file_vpcdns_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_vpcdns_proto_goTypes = []any{
	(*Binding)(nil),          // 0: apoxy.workerd.v1.Binding
	(*ApplyDNSRequest)(nil),  // 1: apoxy.workerd.v1.ApplyDNSRequest
	(*ApplyDNSResponse)(nil), // 2: apoxy.workerd.v1.ApplyDNSResponse
}
var file_vpcdns_proto_depIdxs = []int32{
	0, // 0: apoxy.workerd.v1.ApplyDNSRequest.bindings:type_name -> apoxy.workerd.v1.Binding
	1, // 1: apoxy.workerd.v1.DNSConfig.ApplyDNS:input_type -> apoxy.workerd.v1.ApplyDNSRequest
	2, // 2: apoxy.workerd.v1.DNSConfig.ApplyDNS:output_type -> apoxy.workerd.v1.ApplyDNSResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_vpcdns_proto_init() }
func file_vpcdns_proto_init() {
	if File_vpcdns_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vpcdns_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vpcdns_proto_goTypes,
		DependencyIndexes: file_vpcdns_proto_depIdxs,
		MessageInfos:      file_vpcdns_proto_msgTypes,
	}.Build()
	File_vpcdns_proto = out.File
	file_vpcdns_proto_rawDesc = nil
	file_vpcdns_proto_goTypes = nil
	file_vpcdns_proto_depIdxs = nil
}
