// SPDX-License-Identifier: AGPL-3.0-only
//
// DNSConfig is the worker-side sink of the workerd VPC name plane: the
// manager's per-project infra watch compiles the bindings the project's
// workers may resolve and reach (tunnel endpoints today, VPC-bound Services
// later) and pushes them here over the same per-tenant unix domain socket
// the egress config plane uses. The resident serves the pushed state from
// its own DNS listener (the abstract unixgram socket sealed into the
// sandbox's InitStr) and derives the egress SSRF carve-out from the
// bindings' reachable prefixes.
//
// Like EgressConfig, this drives host-resident state only, never the Sentry:
// the Sentry's :53 forwarder is pointed at the resident's listener once at
// boot and needs no live channel. Applies are idempotent and
// last-writer-wins, ordered by generation.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.28.3
// source: vpcdns.proto

package workerdv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DNSConfig_ApplyDNS_FullMethodName = "/apoxy.workerd.v1.DNSConfig/ApplyDNS"
)

// DNSConfigClient is the client API for DNSConfig service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DNSConfig applies the VPC name plane to a tenant's resident.
type DNSConfigClient interface {
	// ApplyDNS installs the resident's full VPC name plane: the bindings the
	// project's workers can resolve and reach, plus the zones the resolver is
	// authoritative for. The request carries the WHOLE desired state — a
	// binding absent from the request is deleted, so the pusher stays
	// level-triggered and deletions need no tombstones. Idempotent; a request
	// whose generation is older than the last applied one is ignored (the
	// response echoes the retained generation).
	ApplyDNS(ctx context.Context, in *ApplyDNSRequest, opts ...grpc.CallOption) (*ApplyDNSResponse, error)
}

type dNSConfigClient struct {
	cc grpc.ClientConnInterface
}

func NewDNSConfigClient(cc grpc.ClientConnInterface) DNSConfigClient {
	return &dNSConfigClient{cc}
}

func (c *dNSConfigClient) ApplyDNS(ctx context.Context, in *ApplyDNSRequest, opts ...grpc.CallOption) (*ApplyDNSResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyDNSResponse)
	err := c.cc.Invoke(ctx, DNSConfig_ApplyDNS_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DNSConfigServer is the server API for DNSConfig service.
// All implementations must embed UnimplementedDNSConfigServer
// for forward compatibility.
//
// DNSConfig applies the VPC name plane to a tenant's resident.
type DNSConfigServer interface {
	// ApplyDNS installs the resident's full VPC name plane: the bindings the
	// project's workers can resolve and reach, plus the zones the resolver is
	// authoritative for. The request carries the WHOLE desired state — a
	// binding absent from the request is deleted, so the pusher stays
	// level-triggered and deletions need no tombstones. Idempotent; a request
	// whose generation is older than the last applied one is ignored (the
	// response echoes the retained generation).
	ApplyDNS(context.Context, *ApplyDNSRequest) (*ApplyDNSResponse, error)
	mustEmbedUnimplementedDNSConfigServer()
}

// UnimplementedDNSConfigServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDNSConfigServer struct{}

func (UnimplementedDNSConfigServer) ApplyDNS(context.Context, *ApplyDNSRequest) (*ApplyDNSResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyDNS not implemented")
}
func (UnimplementedDNSConfigServer) mustEmbedUnimplementedDNSConfigServer() {}
func (UnimplementedDNSConfigServer) testEmbeddedByValue()                   {}

// UnsafeDNSConfigServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DNSConfigServer will
// result in compilation errors.
type UnsafeDNSConfigServer interface {
	mustEmbedUnimplementedDNSConfigServer()
}

func RegisterDNSConfigServer(s grpc.ServiceRegistrar, srv DNSConfigServer) {
	// If the following call panics, it indicates UnimplementedDNSConfigServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DNSConfig_ServiceDesc, srv)
}

func _DNSConfig_ApplyDNS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyDNSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DNSConfigServer).ApplyDNS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DNSConfig_ApplyDNS_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DNSConfigServer).ApplyDNS(ctx, req.(*ApplyDNSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DNSConfig_ServiceDesc is the grpc.ServiceDesc for DNSConfig service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DNSConfig_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "apoxy.workerd.v1.DNSConfig",
	HandlerType: (*DNSConfigServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ApplyDNS",
			Handler:    _DNSConfig_ApplyDNS_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vpcdns.proto",
}
