/*
Copyright 2026 Apoxy, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/apoxy-dev/apoxy/api/vpc/v1alpha1"
	vpcv1alpha1 "github.com/apoxy-dev/apoxy/client/versioned/typed/vpc/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeVPCServices implements VPCServiceInterface
type fakeVPCServices struct {
	*gentype.FakeClientWithList[*v1alpha1.VPCService, *v1alpha1.VPCServiceList]
	Fake *FakeVpcV1alpha1
}

func newFakeVPCServices(fake *FakeVpcV1alpha1) vpcv1alpha1.VPCServiceInterface {
	return &fakeVPCServices{
		gentype.NewFakeClientWithList[*v1alpha1.VPCService, *v1alpha1.VPCServiceList](
			fake.Fake,
			"",
			v1alpha1.SchemeGroupVersion.WithResource("vpcservices"),
			v1alpha1.SchemeGroupVersion.WithKind("VPCService"),
			func() *v1alpha1.VPCService { return &v1alpha1.VPCService{} },
			func() *v1alpha1.VPCServiceList { return &v1alpha1.VPCServiceList{} },
			func(dst, src *v1alpha1.VPCServiceList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.VPCServiceList) []*v1alpha1.VPCService { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.VPCServiceList, items []*v1alpha1.VPCService) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
