/*
Copyright 2026 Apoxy, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	computev1alpha1 "github.com/apoxy-dev/apoxy/api/compute/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ServiceRevisionLister helps list ServiceRevisions.
// All objects returned here must be treated as read-only.
type ServiceRevisionLister interface {
	// List lists all ServiceRevisions in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*computev1alpha1.ServiceRevision, err error)
	// Get retrieves the ServiceRevision from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*computev1alpha1.ServiceRevision, error)
	ServiceRevisionListerExpansion
}

// serviceRevisionLister implements the ServiceRevisionLister interface.
type serviceRevisionLister struct {
	listers.ResourceIndexer[*computev1alpha1.ServiceRevision]
}

// NewServiceRevisionLister returns a new ServiceRevisionLister.
func NewServiceRevisionLister(indexer cache.Indexer) ServiceRevisionLister {
	return &serviceRevisionLister{listers.New[*computev1alpha1.ServiceRevision](indexer, computev1alpha1.Resource("servicerevision"))}
}
