receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:{{.OTLPPort}}

processors:
  batch:
    timeout: 5s
    send_batch_size: 1000

exporters:
  debug:
{{- if .EnableClickHouse }}
  clickhouse:
    endpoint: {{.ClickHouseAddr}}
    database: {{.ClickHouseDatabase}}
{{- end }}
{{- if .OTLPTracesEndpoint }}
  otlp:
    endpoint: {{.OTLPTracesEndpoint}}
{{- if eq .OTLPTracesProtocol "grpc" }}
    tls:
      insecure: {{.OTLPTracesInsecure}}
{{- if .OTLPTracesCertificate }}
      cert_file: {{.OTLPTracesCertificate}}
{{- end }}
{{- if and .OTLPTracesClientKey .OTLPTracesClientCertificate }}
      key_file: {{.OTLPTracesClientKey}}
      client_ca_file: {{.OTLPTracesClientCertificate}}
{{- end }}
{{- else if eq .OTLPTracesProtocol "http/protobuf" }}
    protocol: http/protobuf
{{- else if eq .OTLPTracesProtocol "http/json" }}
    protocol: http/json
{{- end }}
{{- end }}

extensions:
  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions:
  - zpages
  pipelines:
    traces:
      receivers:
      - otlp
      processors:
      - batch
      exporters:
      - debug
{{- if .EnableClickHouse }}
      - clickhouse
{{- end }}
{{- if .OTLPTracesEndpoint }}
      - otlp
{{- end }}
