receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:{{.OTLPPort}}

processors:
  batch:
    timeout: 5s
    send_batch_size: 1000

exporters:
  debug:
{{- if .EnableClickHouse }}
  clickhouse:
    endpoint: {{.ClickHouseAddr}}
    database: {{.ClickHouseDatabase}}
{{- end }}

extensions:
  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions:
  - zpages
  pipelines:
    traces:
      receivers:
      - otlp
      processors:
      - batch
      exporters:
      - debug
{{- if .EnableClickHouse }}
      - clickhouse
{{- end }}
