/*
Copyright 2026 Apoxy, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha

import (
	corev1alpha "github.com/apoxy-dev/apoxy/api/core/v1alpha"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// DomainZoneLister helps list DomainZones.
// All objects returned here must be treated as read-only.
type DomainZoneLister interface {
	// List lists all DomainZones in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*corev1alpha.DomainZone, err error)
	// Get retrieves the DomainZone from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*corev1alpha.DomainZone, error)
	DomainZoneListerExpansion
}

// domainZoneLister implements the DomainZoneLister interface.
type domainZoneLister struct {
	listers.ResourceIndexer[*corev1alpha.DomainZone]
}

// NewDomainZoneLister returns a new DomainZoneLister.
func NewDomainZoneLister(indexer cache.Indexer) DomainZoneLister {
	return &domainZoneLister{listers.New[*corev1alpha.DomainZone](indexer, corev1alpha.Resource("domainzone"))}
}
