/*
Copyright 2026 Apoxy, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha

import (
	corev1alpha "github.com/apoxy-dev/apoxy/api/core/v1alpha"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// SecretStoreLister helps list SecretStores.
// All objects returned here must be treated as read-only.
type SecretStoreLister interface {
	// List lists all SecretStores in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*corev1alpha.SecretStore, err error)
	// Get retrieves the SecretStore from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*corev1alpha.SecretStore, error)
	SecretStoreListerExpansion
}

// secretStoreLister implements the SecretStoreLister interface.
type secretStoreLister struct {
	listers.ResourceIndexer[*corev1alpha.SecretStore]
}

// NewSecretStoreLister returns a new SecretStoreLister.
func NewSecretStoreLister(indexer cache.Indexer) SecretStoreLister {
	return &secretStoreLister{listers.New[*corev1alpha.SecretStore](indexer, corev1alpha.Resource("secretstore"))}
}
