/*
Copyright 2026 Apoxy, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha2

import (
	context "context"
	time "time"

	apiextensionsv1alpha2 "github.com/apoxy-dev/apoxy/api/extensions/v1alpha2"
	internalinterfaces "github.com/apoxy-dev/apoxy/client/informers/internalinterfaces"
	extensionsv1alpha2 "github.com/apoxy-dev/apoxy/client/listers/extensions/v1alpha2"
	versioned "github.com/apoxy-dev/apoxy/client/versioned"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// HTTPRouteFilterInformer provides access to a shared informer and lister for
// HTTPRouteFilters.
type HTTPRouteFilterInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() extensionsv1alpha2.HTTPRouteFilterLister
}

type hTTPRouteFilterInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewHTTPRouteFilterInformer constructs a new informer for HTTPRouteFilter type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewHTTPRouteFilterInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredHTTPRouteFilterInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredHTTPRouteFilterInformer constructs a new informer for HTTPRouteFilter type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredHTTPRouteFilterInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ExtensionsV1alpha2().HTTPRouteFilters().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ExtensionsV1alpha2().HTTPRouteFilters().Watch(context.TODO(), options)
			},
		},
		&apiextensionsv1alpha2.HTTPRouteFilter{},
		resyncPeriod,
		indexers,
	)
}

func (f *hTTPRouteFilterInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredHTTPRouteFilterInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *hTTPRouteFilterInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apiextensionsv1alpha2.HTTPRouteFilter{}, f.defaultInformer)
}

func (f *hTTPRouteFilterInformer) Lister() extensionsv1alpha2.HTTPRouteFilterLister {
	return extensionsv1alpha2.NewHTTPRouteFilterLister(f.Informer().GetIndexer())
}
