/*
Copyright 2026 Apoxy, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	metricsv1alpha1 "github.com/apoxy-dev/apoxy/api/metrics/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// MetricLister helps list Metrics.
// All objects returned here must be treated as read-only.
type MetricLister interface {
	// List lists all Metrics in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*metricsv1alpha1.Metric, err error)
	// Get retrieves the Metric from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*metricsv1alpha1.Metric, error)
	MetricListerExpansion
}

// metricLister implements the MetricLister interface.
type metricLister struct {
	listers.ResourceIndexer[*metricsv1alpha1.Metric]
}

// NewMetricLister returns a new MetricLister.
func NewMetricLister(indexer cache.Indexer) MetricLister {
	return &metricLister{listers.New[*metricsv1alpha1.Metric](indexer, metricsv1alpha1.Resource("metric"))}
}
