/*
Copyright 2026 Apoxy, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	metricsv1alpha1 "github.com/apoxy-dev/apoxy/api/metrics/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// MetricSourceLister helps list MetricSources.
// All objects returned here must be treated as read-only.
type MetricSourceLister interface {
	// List lists all MetricSources in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*metricsv1alpha1.MetricSource, err error)
	// Get retrieves the MetricSource from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*metricsv1alpha1.MetricSource, error)
	MetricSourceListerExpansion
}

// metricSourceLister implements the MetricSourceLister interface.
type metricSourceLister struct {
	listers.ResourceIndexer[*metricsv1alpha1.MetricSource]
}

// NewMetricSourceLister returns a new MetricSourceLister.
func NewMetricSourceLister(indexer cache.Indexer) MetricSourceLister {
	return &metricSourceLister{listers.New[*metricsv1alpha1.MetricSource](indexer, metricsv1alpha1.Resource("metricsource"))}
}
