/*
Copyright 2026 Apoxy, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	computev1alpha1 "github.com/apoxy-dev/apoxy/api/compute/v1alpha1"
	scheme "github.com/apoxy-dev/apoxy/client/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// BuildsGetter has a method to return a BuildInterface.
// A group's client should implement this interface.
type BuildsGetter interface {
	Builds() BuildInterface
}

// BuildInterface has methods to work with Build resources.
type BuildInterface interface {
	Create(ctx context.Context, build *computev1alpha1.Build, opts v1.CreateOptions) (*computev1alpha1.Build, error)
	Update(ctx context.Context, build *computev1alpha1.Build, opts v1.UpdateOptions) (*computev1alpha1.Build, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, build *computev1alpha1.Build, opts v1.UpdateOptions) (*computev1alpha1.Build, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*computev1alpha1.Build, error)
	List(ctx context.Context, opts v1.ListOptions) (*computev1alpha1.BuildList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *computev1alpha1.Build, err error)
	BuildExpansion
}

// builds implements BuildInterface
type builds struct {
	*gentype.ClientWithList[*computev1alpha1.Build, *computev1alpha1.BuildList]
}

// newBuilds returns a Builds
func newBuilds(c *ComputeV1alpha1Client) *builds {
	return &builds{
		gentype.NewClientWithList[*computev1alpha1.Build, *computev1alpha1.BuildList](
			"builds",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *computev1alpha1.Build { return &computev1alpha1.Build{} },
			func() *computev1alpha1.BuildList { return &computev1alpha1.BuildList{} },
		),
	}
}
