/*
Copyright 2026 Apoxy, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	computev1alpha1 "github.com/apoxy-dev/apoxy/api/compute/v1alpha1"
	scheme "github.com/apoxy-dev/apoxy/client/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// EgressRoutesGetter has a method to return a EgressRouteInterface.
// A group's client should implement this interface.
type EgressRoutesGetter interface {
	EgressRoutes() EgressRouteInterface
}

// EgressRouteInterface has methods to work with EgressRoute resources.
type EgressRouteInterface interface {
	Create(ctx context.Context, egressRoute *computev1alpha1.EgressRoute, opts v1.CreateOptions) (*computev1alpha1.EgressRoute, error)
	Update(ctx context.Context, egressRoute *computev1alpha1.EgressRoute, opts v1.UpdateOptions) (*computev1alpha1.EgressRoute, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, egressRoute *computev1alpha1.EgressRoute, opts v1.UpdateOptions) (*computev1alpha1.EgressRoute, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*computev1alpha1.EgressRoute, error)
	List(ctx context.Context, opts v1.ListOptions) (*computev1alpha1.EgressRouteList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *computev1alpha1.EgressRoute, err error)
	EgressRouteExpansion
}

// egressRoutes implements EgressRouteInterface
type egressRoutes struct {
	*gentype.ClientWithList[*computev1alpha1.EgressRoute, *computev1alpha1.EgressRouteList]
}

// newEgressRoutes returns a EgressRoutes
func newEgressRoutes(c *ComputeV1alpha1Client) *egressRoutes {
	return &egressRoutes{
		gentype.NewClientWithList[*computev1alpha1.EgressRoute, *computev1alpha1.EgressRouteList](
			"egressroutes",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *computev1alpha1.EgressRoute { return &computev1alpha1.EgressRoute{} },
			func() *computev1alpha1.EgressRouteList { return &computev1alpha1.EgressRouteList{} },
		),
	}
}
