/*
Copyright 2026 Apoxy, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha2

import (
	corev1alpha2 "github.com/apoxy-dev/apoxy/api/core/v1alpha2"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// BackendLister helps list Backends.
// All objects returned here must be treated as read-only.
type BackendLister interface {
	// List lists all Backends in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*corev1alpha2.Backend, err error)
	// Get retrieves the Backend from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*corev1alpha2.Backend, error)
	BackendListerExpansion
}

// backendLister implements the BackendLister interface.
type backendLister struct {
	listers.ResourceIndexer[*corev1alpha2.Backend]
}

// NewBackendLister returns a new BackendLister.
func NewBackendLister(indexer cache.Indexer) BackendLister {
	return &backendLister{listers.New[*corev1alpha2.Backend](indexer, corev1alpha2.Resource("backend"))}
}
