/*
Copyright 2026 Apoxy, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha2

import (
	corev1alpha2 "github.com/apoxy-dev/apoxy/api/core/v1alpha2"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// CloudMonitoringIntegrationLister helps list CloudMonitoringIntegrations.
// All objects returned here must be treated as read-only.
type CloudMonitoringIntegrationLister interface {
	// List lists all CloudMonitoringIntegrations in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*corev1alpha2.CloudMonitoringIntegration, err error)
	// Get retrieves the CloudMonitoringIntegration from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*corev1alpha2.CloudMonitoringIntegration, error)
	CloudMonitoringIntegrationListerExpansion
}

// cloudMonitoringIntegrationLister implements the CloudMonitoringIntegrationLister interface.
type cloudMonitoringIntegrationLister struct {
	listers.ResourceIndexer[*corev1alpha2.CloudMonitoringIntegration]
}

// NewCloudMonitoringIntegrationLister returns a new CloudMonitoringIntegrationLister.
func NewCloudMonitoringIntegrationLister(indexer cache.Indexer) CloudMonitoringIntegrationLister {
	return &cloudMonitoringIntegrationLister{listers.New[*corev1alpha2.CloudMonitoringIntegration](indexer, corev1alpha2.Resource("cloudmonitoringintegration"))}
}
