/*
Copyright 2025 Apoxy, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha2

import (
	v1alpha2 "github.com/apoxy-dev/apoxy/api/core/v1alpha2"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// TunnelLister helps list Tunnels.
// All objects returned here must be treated as read-only.
type TunnelLister interface {
	// List lists all Tunnels in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha2.Tunnel, err error)
	// Get retrieves the Tunnel from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha2.Tunnel, error)
	TunnelListerExpansion
}

// tunnelLister implements the TunnelLister interface.
type tunnelLister struct {
	indexer cache.Indexer
}

// NewTunnelLister returns a new TunnelLister.
func NewTunnelLister(indexer cache.Indexer) TunnelLister {
	return &tunnelLister{indexer: indexer}
}

// List lists all Tunnels in the indexer.
func (s *tunnelLister) List(selector labels.Selector) (ret []*v1alpha2.Tunnel, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha2.Tunnel))
	})
	return ret, err
}

// Get retrieves the Tunnel from the index for a given name.
func (s *tunnelLister) Get(name string) (*v1alpha2.Tunnel, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha2.Resource("tunnel"), name)
	}
	return obj.(*v1alpha2.Tunnel), nil
}
