/*
Copyright 2026 Apoxy, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	policyv1alpha1 "github.com/apoxy-dev/apoxy/api/policy/v1alpha1"
	scheme "github.com/apoxy-dev/apoxy/client/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// RateLimitsGetter has a method to return a RateLimitInterface.
// A group's client should implement this interface.
type RateLimitsGetter interface {
	RateLimits() RateLimitInterface
}

// RateLimitInterface has methods to work with RateLimit resources.
type RateLimitInterface interface {
	Create(ctx context.Context, rateLimit *policyv1alpha1.RateLimit, opts v1.CreateOptions) (*policyv1alpha1.RateLimit, error)
	Update(ctx context.Context, rateLimit *policyv1alpha1.RateLimit, opts v1.UpdateOptions) (*policyv1alpha1.RateLimit, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, rateLimit *policyv1alpha1.RateLimit, opts v1.UpdateOptions) (*policyv1alpha1.RateLimit, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*policyv1alpha1.RateLimit, error)
	List(ctx context.Context, opts v1.ListOptions) (*policyv1alpha1.RateLimitList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *policyv1alpha1.RateLimit, err error)
	RateLimitExpansion
}

// rateLimits implements RateLimitInterface
type rateLimits struct {
	*gentype.ClientWithList[*policyv1alpha1.RateLimit, *policyv1alpha1.RateLimitList]
}

// newRateLimits returns a RateLimits
func newRateLimits(c *PolicyV1alpha1Client) *rateLimits {
	return &rateLimits{
		gentype.NewClientWithList[*policyv1alpha1.RateLimit, *policyv1alpha1.RateLimitList](
			"ratelimits",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *policyv1alpha1.RateLimit { return &policyv1alpha1.RateLimit{} },
			func() *policyv1alpha1.RateLimitList { return &policyv1alpha1.RateLimitList{} },
		),
	}
}
