/**
 * APO-765 — schema.d.ts codegen (openapi-typescript).
 *
 * Generates `apps/apoxy-console/src/schema/schema.d.ts` from the apiserver
 * OpenAPI. These are apoxy-specific types, so they live in the apoxy app rather
 * than in the app-agnostic `@apoxy/console-core` (CLRK generates its own).
 * The committed output is the source of truth; this is not fetched at runtime.
 *
 * Source resolution (offline preferred — hermetic CI, no running apiserver):
 *   1. `console/openapi.json`, rendered offline from `api/generated/zz_generated.openapi.go`
 *      by the `cmd/openapi-dump` Go command (APO-765). Regenerate the spec with:
 *        go run ./cmd/openapi-dump -o console/openapi.json -title "Apoxy Console API" -version v0
 *      (run from the repo root). Both the spec and this file's output are committed;
 *      CI regenerates and diffs them to catch drift.
 *   2. Fallback: a live apiserver's OpenAPI at $APOXY_OPENAPI_URL (e.g. the dashboard's
 *      old runtime-discovery flow against https://localhost:9050/openapi/v3).
 */
import { access, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import openapiTS, { astToString } from 'openapi-typescript'

const here = dirname(fileURLToPath(import.meta.url))
const OUT = resolve(here, '../apps/apoxy-console/src/schema/schema.d.ts')
const LOCAL_SPEC = resolve(here, '../openapi.json')
const REMOTE = process.env.APOXY_OPENAPI_URL

async function resolveSource(): Promise<URL> {
  try {
    await access(LOCAL_SPEC)
    return new URL(`file://${LOCAL_SPEC}`)
  } catch {
    // no local spec
  }
  if (REMOTE) return new URL(REMOTE)
  throw new Error(
    'No OpenAPI source. Render console/openapi.json offline from ' +
      'api/generated/zz_generated.openapi.go (preferred), or set APOXY_OPENAPI_URL.',
  )
}

const source = await resolveSource()
const ast = await openapiTS(source)
const banner =
  '// GENERATED by console/scripts/generate-schema.ts (openapi-typescript) — do not edit by hand.\n'
await writeFile(OUT, banner + astToString(ast))
console.log(`Wrote ${OUT} from ${source.href}`)
