/*
Copyright 2026 Apoxy, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package informers

import (
	fmt "fmt"

	v1alpha1 "github.com/apoxy-dev/apoxy/api/controllers/v1alpha1"
	v1alpha "github.com/apoxy-dev/apoxy/api/core/v1alpha"
	v1alpha2 "github.com/apoxy-dev/apoxy/api/core/v1alpha2"
	extensionsv1alpha1 "github.com/apoxy-dev/apoxy/api/extensions/v1alpha1"
	extensionsv1alpha2 "github.com/apoxy-dev/apoxy/api/extensions/v1alpha2"
	v1 "github.com/apoxy-dev/apoxy/api/gateway/v1"
	gatewayv1alpha2 "github.com/apoxy-dev/apoxy/api/gateway/v1alpha2"
	policyv1alpha1 "github.com/apoxy-dev/apoxy/api/policy/v1alpha1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	cache "k8s.io/client-go/tools/cache"
)

// GenericInformer is type of SharedIndexInformer which will locate and delegate to other
// sharedInformers based on type
type GenericInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() cache.GenericLister
}

type genericInformer struct {
	informer cache.SharedIndexInformer
	resource schema.GroupResource
}

// Informer returns the SharedIndexInformer.
func (f *genericInformer) Informer() cache.SharedIndexInformer {
	return f.informer
}

// Lister returns the GenericLister.
func (f *genericInformer) Lister() cache.GenericLister {
	return cache.NewGenericLister(f.Informer().GetIndexer(), f.resource)
}

// ForResource gives generic access to a shared informer of the matching type
// TODO extend this to unknown resources with a client pool
func (f *sharedInformerFactory) ForResource(resource schema.GroupVersionResource) (GenericInformer, error) {
	switch resource {
	// Group=controllers.apoxy.dev, Version=v1alpha1
	case v1alpha1.SchemeGroupVersion.WithResource("proxies"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Controllers().V1alpha1().Proxies().Informer()}, nil

		// Group=core.apoxy.dev, Version=v1alpha
	case v1alpha.SchemeGroupVersion.WithResource("backends"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Core().V1alpha().Backends().Informer()}, nil
	case v1alpha.SchemeGroupVersion.WithResource("cloudmonitoringintegrations"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Core().V1alpha().CloudMonitoringIntegrations().Informer()}, nil
	case v1alpha.SchemeGroupVersion.WithResource("domains"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Core().V1alpha().Domains().Informer()}, nil
	case v1alpha.SchemeGroupVersion.WithResource("domainzones"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Core().V1alpha().DomainZones().Informer()}, nil
	case v1alpha.SchemeGroupVersion.WithResource("tunnelnodes"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Core().V1alpha().TunnelNodes().Informer()}, nil

		// Group=core.apoxy.dev, Version=v1alpha2
	case v1alpha2.SchemeGroupVersion.WithResource("backends"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Core().V1alpha2().Backends().Informer()}, nil
	case v1alpha2.SchemeGroupVersion.WithResource("cloudmonitoringintegrations"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Core().V1alpha2().CloudMonitoringIntegrations().Informer()}, nil
	case v1alpha2.SchemeGroupVersion.WithResource("domains"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Core().V1alpha2().Domains().Informer()}, nil
	case v1alpha2.SchemeGroupVersion.WithResource("domainzones"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Core().V1alpha2().DomainZones().Informer()}, nil
	case v1alpha2.SchemeGroupVersion.WithResource("proxies"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Core().V1alpha2().Proxies().Informer()}, nil
	case v1alpha2.SchemeGroupVersion.WithResource("tunnels"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Core().V1alpha2().Tunnels().Informer()}, nil
	case v1alpha2.SchemeGroupVersion.WithResource("tunnelagents"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Core().V1alpha2().TunnelAgents().Informer()}, nil

		// Group=extensions.apoxy.dev, Version=v1alpha1
	case extensionsv1alpha1.SchemeGroupVersion.WithResource("edgefunctions"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Extensions().V1alpha1().EdgeFunctions().Informer()}, nil
	case extensionsv1alpha1.SchemeGroupVersion.WithResource("edgefunctionrevisions"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Extensions().V1alpha1().EdgeFunctionRevisions().Informer()}, nil

		// Group=extensions.apoxy.dev, Version=v1alpha2
	case extensionsv1alpha2.SchemeGroupVersion.WithResource("edgefunctions"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Extensions().V1alpha2().EdgeFunctions().Informer()}, nil
	case extensionsv1alpha2.SchemeGroupVersion.WithResource("edgefunctionrevisions"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Extensions().V1alpha2().EdgeFunctionRevisions().Informer()}, nil

		// Group=gateway.apoxy.dev, Version=v1
	case v1.SchemeGroupVersion.WithResource("grpcroutes"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Gateway().V1().GRPCRoutes().Informer()}, nil
	case v1.SchemeGroupVersion.WithResource("gateways"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Gateway().V1().Gateways().Informer()}, nil
	case v1.SchemeGroupVersion.WithResource("gatewayclasses"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Gateway().V1().GatewayClasses().Informer()}, nil
	case v1.SchemeGroupVersion.WithResource("httproutes"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Gateway().V1().HTTPRoutes().Informer()}, nil

		// Group=gateway.apoxy.dev, Version=v1alpha2
	case gatewayv1alpha2.SchemeGroupVersion.WithResource("tcproutes"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Gateway().V1alpha2().TCPRoutes().Informer()}, nil
	case gatewayv1alpha2.SchemeGroupVersion.WithResource("tlsroutes"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Gateway().V1alpha2().TLSRoutes().Informer()}, nil
	case gatewayv1alpha2.SchemeGroupVersion.WithResource("udproutes"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Gateway().V1alpha2().UDPRoutes().Informer()}, nil

		// Group=policy.apoxy.dev, Version=v1alpha1
	case policyv1alpha1.SchemeGroupVersion.WithResource("ratelimits"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Policy().V1alpha1().RateLimits().Informer()}, nil

	}

	return nil, fmt.Errorf("no informer found for %v", resource)
}
