/*
Copyright 2026 Apoxy, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha3

import (
	context "context"
	time "time"

	apicorev1alpha3 "github.com/apoxy-dev/apoxy/api/core/v1alpha3"
	internalinterfaces "github.com/apoxy-dev/apoxy/client/informers/internalinterfaces"
	corev1alpha3 "github.com/apoxy-dev/apoxy/client/listers/core/v1alpha3"
	versioned "github.com/apoxy-dev/apoxy/client/versioned"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// DomainRecordInformer provides access to a shared informer and lister for
// DomainRecords.
type DomainRecordInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() corev1alpha3.DomainRecordLister
}

type domainRecordInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewDomainRecordInformer constructs a new informer for DomainRecord type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewDomainRecordInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredDomainRecordInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredDomainRecordInformer constructs a new informer for DomainRecord type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredDomainRecordInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CoreV1alpha3().DomainRecords().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CoreV1alpha3().DomainRecords().Watch(context.TODO(), options)
			},
		},
		&apicorev1alpha3.DomainRecord{},
		resyncPeriod,
		indexers,
	)
}

func (f *domainRecordInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredDomainRecordInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *domainRecordInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apicorev1alpha3.DomainRecord{}, f.defaultInformer)
}

func (f *domainRecordInformer) Lister() corev1alpha3.DomainRecordLister {
	return corev1alpha3.NewDomainRecordLister(f.Informer().GetIndexer())
}
