/*
Copyright 2026 Apoxy, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	metricsv1alpha1 "github.com/apoxy-dev/apoxy/api/metrics/v1alpha1"
	scheme "github.com/apoxy-dev/apoxy/client/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// MetricsGetter has a method to return a MetricInterface.
// A group's client should implement this interface.
type MetricsGetter interface {
	Metrics() MetricInterface
}

// MetricInterface has methods to work with Metric resources.
type MetricInterface interface {
	Create(ctx context.Context, metric *metricsv1alpha1.Metric, opts v1.CreateOptions) (*metricsv1alpha1.Metric, error)
	Update(ctx context.Context, metric *metricsv1alpha1.Metric, opts v1.UpdateOptions) (*metricsv1alpha1.Metric, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, metric *metricsv1alpha1.Metric, opts v1.UpdateOptions) (*metricsv1alpha1.Metric, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*metricsv1alpha1.Metric, error)
	List(ctx context.Context, opts v1.ListOptions) (*metricsv1alpha1.MetricList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *metricsv1alpha1.Metric, err error)
	MetricExpansion
}

// metrics implements MetricInterface
type metrics struct {
	*gentype.ClientWithList[*metricsv1alpha1.Metric, *metricsv1alpha1.MetricList]
}

// newMetrics returns a Metrics
func newMetrics(c *MetricsV1alpha1Client) *metrics {
	return &metrics{
		gentype.NewClientWithList[*metricsv1alpha1.Metric, *metricsv1alpha1.MetricList](
			"metrics",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *metricsv1alpha1.Metric { return &metricsv1alpha1.Metric{} },
			func() *metricsv1alpha1.MetricList { return &metricsv1alpha1.MetricList{} },
		),
	}
}
