/*
Copyright 2026 Apoxy, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha2

import (
	context "context"

	extensionsv1alpha2 "github.com/apoxy-dev/apoxy/api/extensions/v1alpha2"
	scheme "github.com/apoxy-dev/apoxy/client/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// DirectResponsesGetter has a method to return a DirectResponseInterface.
// A group's client should implement this interface.
type DirectResponsesGetter interface {
	DirectResponses() DirectResponseInterface
}

// DirectResponseInterface has methods to work with DirectResponse resources.
type DirectResponseInterface interface {
	Create(ctx context.Context, directResponse *extensionsv1alpha2.DirectResponse, opts v1.CreateOptions) (*extensionsv1alpha2.DirectResponse, error)
	Update(ctx context.Context, directResponse *extensionsv1alpha2.DirectResponse, opts v1.UpdateOptions) (*extensionsv1alpha2.DirectResponse, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, directResponse *extensionsv1alpha2.DirectResponse, opts v1.UpdateOptions) (*extensionsv1alpha2.DirectResponse, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*extensionsv1alpha2.DirectResponse, error)
	List(ctx context.Context, opts v1.ListOptions) (*extensionsv1alpha2.DirectResponseList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *extensionsv1alpha2.DirectResponse, err error)
	DirectResponseExpansion
}

// directResponses implements DirectResponseInterface
type directResponses struct {
	*gentype.ClientWithList[*extensionsv1alpha2.DirectResponse, *extensionsv1alpha2.DirectResponseList]
}

// newDirectResponses returns a DirectResponses
func newDirectResponses(c *ExtensionsV1alpha2Client) *directResponses {
	return &directResponses{
		gentype.NewClientWithList[*extensionsv1alpha2.DirectResponse, *extensionsv1alpha2.DirectResponseList](
			"directresponses",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *extensionsv1alpha2.DirectResponse { return &extensionsv1alpha2.DirectResponse{} },
			func() *extensionsv1alpha2.DirectResponseList { return &extensionsv1alpha2.DirectResponseList{} },
		),
	}
}
