/*
Copyright 2026 Apoxy, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha2

import (
	context "context"

	extensionsv1alpha2 "github.com/apoxy-dev/apoxy/api/extensions/v1alpha2"
	scheme "github.com/apoxy-dev/apoxy/client/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// EdgeFunctionRevisionsGetter has a method to return a EdgeFunctionRevisionInterface.
// A group's client should implement this interface.
type EdgeFunctionRevisionsGetter interface {
	EdgeFunctionRevisions() EdgeFunctionRevisionInterface
}

// EdgeFunctionRevisionInterface has methods to work with EdgeFunctionRevision resources.
type EdgeFunctionRevisionInterface interface {
	Create(ctx context.Context, edgeFunctionRevision *extensionsv1alpha2.EdgeFunctionRevision, opts v1.CreateOptions) (*extensionsv1alpha2.EdgeFunctionRevision, error)
	Update(ctx context.Context, edgeFunctionRevision *extensionsv1alpha2.EdgeFunctionRevision, opts v1.UpdateOptions) (*extensionsv1alpha2.EdgeFunctionRevision, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, edgeFunctionRevision *extensionsv1alpha2.EdgeFunctionRevision, opts v1.UpdateOptions) (*extensionsv1alpha2.EdgeFunctionRevision, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*extensionsv1alpha2.EdgeFunctionRevision, error)
	List(ctx context.Context, opts v1.ListOptions) (*extensionsv1alpha2.EdgeFunctionRevisionList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *extensionsv1alpha2.EdgeFunctionRevision, err error)
	EdgeFunctionRevisionExpansion
}

// edgeFunctionRevisions implements EdgeFunctionRevisionInterface
type edgeFunctionRevisions struct {
	*gentype.ClientWithList[*extensionsv1alpha2.EdgeFunctionRevision, *extensionsv1alpha2.EdgeFunctionRevisionList]
}

// newEdgeFunctionRevisions returns a EdgeFunctionRevisions
func newEdgeFunctionRevisions(c *ExtensionsV1alpha2Client) *edgeFunctionRevisions {
	return &edgeFunctionRevisions{
		gentype.NewClientWithList[*extensionsv1alpha2.EdgeFunctionRevision, *extensionsv1alpha2.EdgeFunctionRevisionList](
			"edgefunctionrevisions",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *extensionsv1alpha2.EdgeFunctionRevision { return &extensionsv1alpha2.EdgeFunctionRevision{} },
			func() *extensionsv1alpha2.EdgeFunctionRevisionList {
				return &extensionsv1alpha2.EdgeFunctionRevisionList{}
			},
		),
	}
}
