/*
Copyright 2026 Apoxy, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha3

import (
	context "context"

	corev1alpha3 "github.com/apoxy-dev/apoxy/api/core/v1alpha3"
	scheme "github.com/apoxy-dev/apoxy/client/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// DomainRecordsGetter has a method to return a DomainRecordInterface.
// A group's client should implement this interface.
type DomainRecordsGetter interface {
	DomainRecords() DomainRecordInterface
}

// DomainRecordInterface has methods to work with DomainRecord resources.
type DomainRecordInterface interface {
	Create(ctx context.Context, domainRecord *corev1alpha3.DomainRecord, opts v1.CreateOptions) (*corev1alpha3.DomainRecord, error)
	Update(ctx context.Context, domainRecord *corev1alpha3.DomainRecord, opts v1.UpdateOptions) (*corev1alpha3.DomainRecord, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, domainRecord *corev1alpha3.DomainRecord, opts v1.UpdateOptions) (*corev1alpha3.DomainRecord, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*corev1alpha3.DomainRecord, error)
	List(ctx context.Context, opts v1.ListOptions) (*corev1alpha3.DomainRecordList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *corev1alpha3.DomainRecord, err error)
	DomainRecordExpansion
}

// domainRecords implements DomainRecordInterface
type domainRecords struct {
	*gentype.ClientWithList[*corev1alpha3.DomainRecord, *corev1alpha3.DomainRecordList]
}

// newDomainRecords returns a DomainRecords
func newDomainRecords(c *CoreV1alpha3Client) *domainRecords {
	return &domainRecords{
		gentype.NewClientWithList[*corev1alpha3.DomainRecord, *corev1alpha3.DomainRecordList](
			"domainrecords",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *corev1alpha3.DomainRecord { return &corev1alpha3.DomainRecord{} },
			func() *corev1alpha3.DomainRecordList { return &corev1alpha3.DomainRecordList{} },
		),
	}
}
