apiVersion: controllers.apoxy.dev/v1alpha1
kind: Proxy
metadata:
  name: example
spec:
  provider: unmanaged
  listeners:
    - protocol: TCP
      port: 10000
---
apiVersion: gateway.apoxy.dev/v1
kind: GatewayClass
metadata:
  name: apoxy
spec:
  controllerName: gateway.apoxy.dev/gatewayclass-controller
---
apiVersion: gateway.apoxy.dev/v1
kind: Gateway
metadata:
  name: example
spec:
  gatewayClassName: apoxy
  infrastructure:
    parametersRef:
      kind: Proxy
      name: example
  listeners:
    - protocol: HTTP
      port: 10000
      name: example
---
apiVersion: core.apoxy.dev/v1alpha
kind: Backend
metadata:
  name: example-tun
spec:
  endpoints:
    - fqdn: example.tun.apoxy.net
---
apiVersion: gateway.apoxy.dev/v1
kind: HTTPRoute
metadata:
  name: alpamayo
spec:
  parentRefs:
    - name: example
      port: 10000
      kind: Gateway
  hostnames:
    - '*'
  rules:
    - backendRefs:
        - kind: Backend
          name: example-tun
          port: 8080
---
apiVersion: core.apoxy.dev/v1alpha
kind: TunnelNode
metadata:
  name: example
