/*
Copyright 2026 Apoxy, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	extensionsv1alpha1 "github.com/apoxy-dev/apoxy/api/extensions/v1alpha1"
	scheme "github.com/apoxy-dev/apoxy/client/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// EdgeFunctionsGetter has a method to return a EdgeFunctionInterface.
// A group's client should implement this interface.
type EdgeFunctionsGetter interface {
	EdgeFunctions() EdgeFunctionInterface
}

// EdgeFunctionInterface has methods to work with EdgeFunction resources.
type EdgeFunctionInterface interface {
	Create(ctx context.Context, edgeFunction *extensionsv1alpha1.EdgeFunction, opts v1.CreateOptions) (*extensionsv1alpha1.EdgeFunction, error)
	Update(ctx context.Context, edgeFunction *extensionsv1alpha1.EdgeFunction, opts v1.UpdateOptions) (*extensionsv1alpha1.EdgeFunction, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, edgeFunction *extensionsv1alpha1.EdgeFunction, opts v1.UpdateOptions) (*extensionsv1alpha1.EdgeFunction, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*extensionsv1alpha1.EdgeFunction, error)
	List(ctx context.Context, opts v1.ListOptions) (*extensionsv1alpha1.EdgeFunctionList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *extensionsv1alpha1.EdgeFunction, err error)
	EdgeFunctionExpansion
}

// edgeFunctions implements EdgeFunctionInterface
type edgeFunctions struct {
	*gentype.ClientWithList[*extensionsv1alpha1.EdgeFunction, *extensionsv1alpha1.EdgeFunctionList]
}

// newEdgeFunctions returns a EdgeFunctions
func newEdgeFunctions(c *ExtensionsV1alpha1Client) *edgeFunctions {
	return &edgeFunctions{
		gentype.NewClientWithList[*extensionsv1alpha1.EdgeFunction, *extensionsv1alpha1.EdgeFunctionList](
			"edgefunctions",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *extensionsv1alpha1.EdgeFunction { return &extensionsv1alpha1.EdgeFunction{} },
			func() *extensionsv1alpha1.EdgeFunctionList { return &extensionsv1alpha1.EdgeFunctionList{} },
		),
	}
}
