/*
Copyright 2026 Apoxy, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	gatewayv1 "github.com/apoxy-dev/apoxy/api/gateway/v1"
	scheme "github.com/apoxy-dev/apoxy/client/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// GatewaysGetter has a method to return a GatewayInterface.
// A group's client should implement this interface.
type GatewaysGetter interface {
	Gateways() GatewayInterface
}

// GatewayInterface has methods to work with Gateway resources.
type GatewayInterface interface {
	Create(ctx context.Context, gateway *gatewayv1.Gateway, opts metav1.CreateOptions) (*gatewayv1.Gateway, error)
	Update(ctx context.Context, gateway *gatewayv1.Gateway, opts metav1.UpdateOptions) (*gatewayv1.Gateway, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, gateway *gatewayv1.Gateway, opts metav1.UpdateOptions) (*gatewayv1.Gateway, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*gatewayv1.Gateway, error)
	List(ctx context.Context, opts metav1.ListOptions) (*gatewayv1.GatewayList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *gatewayv1.Gateway, err error)
	GatewayExpansion
}

// gateways implements GatewayInterface
type gateways struct {
	*gentype.ClientWithList[*gatewayv1.Gateway, *gatewayv1.GatewayList]
}

// newGateways returns a Gateways
func newGateways(c *GatewayV1Client) *gateways {
	return &gateways{
		gentype.NewClientWithList[*gatewayv1.Gateway, *gatewayv1.GatewayList](
			"gateways",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *gatewayv1.Gateway { return &gatewayv1.Gateway{} },
			func() *gatewayv1.GatewayList { return &gatewayv1.GatewayList{} },
		),
	}
}
