/*
Copyright 2026 Apoxy, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	gatewayv1 "github.com/apoxy-dev/apoxy/api/gateway/v1"
	scheme "github.com/apoxy-dev/apoxy/client/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// GatewayClassesGetter has a method to return a GatewayClassInterface.
// A group's client should implement this interface.
type GatewayClassesGetter interface {
	GatewayClasses() GatewayClassInterface
}

// GatewayClassInterface has methods to work with GatewayClass resources.
type GatewayClassInterface interface {
	Create(ctx context.Context, gatewayClass *gatewayv1.GatewayClass, opts metav1.CreateOptions) (*gatewayv1.GatewayClass, error)
	Update(ctx context.Context, gatewayClass *gatewayv1.GatewayClass, opts metav1.UpdateOptions) (*gatewayv1.GatewayClass, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, gatewayClass *gatewayv1.GatewayClass, opts metav1.UpdateOptions) (*gatewayv1.GatewayClass, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*gatewayv1.GatewayClass, error)
	List(ctx context.Context, opts metav1.ListOptions) (*gatewayv1.GatewayClassList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *gatewayv1.GatewayClass, err error)
	GatewayClassExpansion
}

// gatewayClasses implements GatewayClassInterface
type gatewayClasses struct {
	*gentype.ClientWithList[*gatewayv1.GatewayClass, *gatewayv1.GatewayClassList]
}

// newGatewayClasses returns a GatewayClasses
func newGatewayClasses(c *GatewayV1Client) *gatewayClasses {
	return &gatewayClasses{
		gentype.NewClientWithList[*gatewayv1.GatewayClass, *gatewayv1.GatewayClassList](
			"gatewayclasses",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *gatewayv1.GatewayClass { return &gatewayv1.GatewayClass{} },
			func() *gatewayv1.GatewayClassList { return &gatewayv1.GatewayClassList{} },
		),
	}
}
