/*
Copyright 2025 Apoxy, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha2 "github.com/apoxy-dev/apoxy/api/core/v1alpha2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeTunnels implements TunnelInterface
type FakeTunnels struct {
	Fake *FakeCoreV1alpha2
}

var tunnelsResource = v1alpha2.SchemeGroupVersion.WithResource("tunnels")

var tunnelsKind = v1alpha2.SchemeGroupVersion.WithKind("Tunnel")

// Get takes name of the tunnel, and returns the corresponding tunnel object, and an error if there is any.
func (c *FakeTunnels) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha2.Tunnel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(tunnelsResource, name), &v1alpha2.Tunnel{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.Tunnel), err
}

// List takes label and field selectors, and returns the list of Tunnels that match those selectors.
func (c *FakeTunnels) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha2.TunnelList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(tunnelsResource, tunnelsKind, opts), &v1alpha2.TunnelList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha2.TunnelList{ListMeta: obj.(*v1alpha2.TunnelList).ListMeta}
	for _, item := range obj.(*v1alpha2.TunnelList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested tunnels.
func (c *FakeTunnels) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(tunnelsResource, opts))
}

// Create takes the representation of a tunnel and creates it.  Returns the server's representation of the tunnel, and an error, if there is any.
func (c *FakeTunnels) Create(ctx context.Context, tunnel *v1alpha2.Tunnel, opts v1.CreateOptions) (result *v1alpha2.Tunnel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(tunnelsResource, tunnel), &v1alpha2.Tunnel{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.Tunnel), err
}

// Update takes the representation of a tunnel and updates it. Returns the server's representation of the tunnel, and an error, if there is any.
func (c *FakeTunnels) Update(ctx context.Context, tunnel *v1alpha2.Tunnel, opts v1.UpdateOptions) (result *v1alpha2.Tunnel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(tunnelsResource, tunnel), &v1alpha2.Tunnel{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.Tunnel), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeTunnels) UpdateStatus(ctx context.Context, tunnel *v1alpha2.Tunnel, opts v1.UpdateOptions) (*v1alpha2.Tunnel, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(tunnelsResource, "status", tunnel), &v1alpha2.Tunnel{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.Tunnel), err
}

// Delete takes name of the tunnel and deletes it. Returns an error if one occurs.
func (c *FakeTunnels) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(tunnelsResource, name, opts), &v1alpha2.Tunnel{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeTunnels) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(tunnelsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha2.TunnelList{})
	return err
}

// Patch applies the patch and returns the patched tunnel.
func (c *FakeTunnels) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha2.Tunnel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(tunnelsResource, name, pt, data, subresources...), &v1alpha2.Tunnel{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.Tunnel), err
}
