/*
Copyright 2026 Apoxy, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha2

import (
	context "context"
	time "time"

	apigatewayv1alpha2 "github.com/apoxy-dev/apoxy/api/gateway/v1alpha2"
	internalinterfaces "github.com/apoxy-dev/apoxy/client/informers/internalinterfaces"
	gatewayv1alpha2 "github.com/apoxy-dev/apoxy/client/listers/gateway/v1alpha2"
	versioned "github.com/apoxy-dev/apoxy/client/versioned"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// UDPRouteInformer provides access to a shared informer and lister for
// UDPRoutes.
type UDPRouteInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() gatewayv1alpha2.UDPRouteLister
}

type uDPRouteInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewUDPRouteInformer constructs a new informer for UDPRoute type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewUDPRouteInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredUDPRouteInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredUDPRouteInformer constructs a new informer for UDPRoute type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredUDPRouteInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.GatewayV1alpha2().UDPRoutes().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.GatewayV1alpha2().UDPRoutes().Watch(context.TODO(), options)
			},
		},
		&apigatewayv1alpha2.UDPRoute{},
		resyncPeriod,
		indexers,
	)
}

func (f *uDPRouteInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredUDPRouteInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *uDPRouteInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apigatewayv1alpha2.UDPRoute{}, f.defaultInformer)
}

func (f *uDPRouteInformer) Lister() gatewayv1alpha2.UDPRouteLister {
	return gatewayv1alpha2.NewUDPRouteLister(f.Informer().GetIndexer())
}
