/*
Copyright 2026 Apoxy, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha2

import (
	context "context"

	gatewayv1alpha2 "github.com/apoxy-dev/apoxy/api/gateway/v1alpha2"
	scheme "github.com/apoxy-dev/apoxy/client/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// TCPRoutesGetter has a method to return a TCPRouteInterface.
// A group's client should implement this interface.
type TCPRoutesGetter interface {
	TCPRoutes() TCPRouteInterface
}

// TCPRouteInterface has methods to work with TCPRoute resources.
type TCPRouteInterface interface {
	Create(ctx context.Context, tCPRoute *gatewayv1alpha2.TCPRoute, opts v1.CreateOptions) (*gatewayv1alpha2.TCPRoute, error)
	Update(ctx context.Context, tCPRoute *gatewayv1alpha2.TCPRoute, opts v1.UpdateOptions) (*gatewayv1alpha2.TCPRoute, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, tCPRoute *gatewayv1alpha2.TCPRoute, opts v1.UpdateOptions) (*gatewayv1alpha2.TCPRoute, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*gatewayv1alpha2.TCPRoute, error)
	List(ctx context.Context, opts v1.ListOptions) (*gatewayv1alpha2.TCPRouteList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *gatewayv1alpha2.TCPRoute, err error)
	TCPRouteExpansion
}

// tCPRoutes implements TCPRouteInterface
type tCPRoutes struct {
	*gentype.ClientWithList[*gatewayv1alpha2.TCPRoute, *gatewayv1alpha2.TCPRouteList]
}

// newTCPRoutes returns a TCPRoutes
func newTCPRoutes(c *GatewayV1alpha2Client) *tCPRoutes {
	return &tCPRoutes{
		gentype.NewClientWithList[*gatewayv1alpha2.TCPRoute, *gatewayv1alpha2.TCPRouteList](
			"tcproutes",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *gatewayv1alpha2.TCPRoute { return &gatewayv1alpha2.TCPRoute{} },
			func() *gatewayv1alpha2.TCPRouteList { return &gatewayv1alpha2.TCPRouteList{} },
		),
	}
}
