/*
Copyright 2026 Apoxy, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha2

import (
	context "context"

	gatewayv1alpha2 "github.com/apoxy-dev/apoxy/api/gateway/v1alpha2"
	scheme "github.com/apoxy-dev/apoxy/client/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// UDPRoutesGetter has a method to return a UDPRouteInterface.
// A group's client should implement this interface.
type UDPRoutesGetter interface {
	UDPRoutes() UDPRouteInterface
}

// UDPRouteInterface has methods to work with UDPRoute resources.
type UDPRouteInterface interface {
	Create(ctx context.Context, uDPRoute *gatewayv1alpha2.UDPRoute, opts v1.CreateOptions) (*gatewayv1alpha2.UDPRoute, error)
	Update(ctx context.Context, uDPRoute *gatewayv1alpha2.UDPRoute, opts v1.UpdateOptions) (*gatewayv1alpha2.UDPRoute, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, uDPRoute *gatewayv1alpha2.UDPRoute, opts v1.UpdateOptions) (*gatewayv1alpha2.UDPRoute, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*gatewayv1alpha2.UDPRoute, error)
	List(ctx context.Context, opts v1.ListOptions) (*gatewayv1alpha2.UDPRouteList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *gatewayv1alpha2.UDPRoute, err error)
	UDPRouteExpansion
}

// uDPRoutes implements UDPRouteInterface
type uDPRoutes struct {
	*gentype.ClientWithList[*gatewayv1alpha2.UDPRoute, *gatewayv1alpha2.UDPRouteList]
}

// newUDPRoutes returns a UDPRoutes
func newUDPRoutes(c *GatewayV1alpha2Client) *uDPRoutes {
	return &uDPRoutes{
		gentype.NewClientWithList[*gatewayv1alpha2.UDPRoute, *gatewayv1alpha2.UDPRouteList](
			"udproutes",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *gatewayv1alpha2.UDPRoute { return &gatewayv1alpha2.UDPRoute{} },
			func() *gatewayv1alpha2.UDPRouteList { return &gatewayv1alpha2.UDPRouteList{} },
		),
	}
}
