/*
Copyright 2026 Apoxy, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha

import (
	context "context"

	corev1alpha "github.com/apoxy-dev/apoxy/api/core/v1alpha"
	scheme "github.com/apoxy-dev/apoxy/client/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// CloudMonitoringIntegrationsGetter has a method to return a CloudMonitoringIntegrationInterface.
// A group's client should implement this interface.
type CloudMonitoringIntegrationsGetter interface {
	CloudMonitoringIntegrations() CloudMonitoringIntegrationInterface
}

// CloudMonitoringIntegrationInterface has methods to work with CloudMonitoringIntegration resources.
type CloudMonitoringIntegrationInterface interface {
	Create(ctx context.Context, cloudMonitoringIntegration *corev1alpha.CloudMonitoringIntegration, opts v1.CreateOptions) (*corev1alpha.CloudMonitoringIntegration, error)
	Update(ctx context.Context, cloudMonitoringIntegration *corev1alpha.CloudMonitoringIntegration, opts v1.UpdateOptions) (*corev1alpha.CloudMonitoringIntegration, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, cloudMonitoringIntegration *corev1alpha.CloudMonitoringIntegration, opts v1.UpdateOptions) (*corev1alpha.CloudMonitoringIntegration, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*corev1alpha.CloudMonitoringIntegration, error)
	List(ctx context.Context, opts v1.ListOptions) (*corev1alpha.CloudMonitoringIntegrationList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *corev1alpha.CloudMonitoringIntegration, err error)
	CloudMonitoringIntegrationExpansion
}

// cloudMonitoringIntegrations implements CloudMonitoringIntegrationInterface
type cloudMonitoringIntegrations struct {
	*gentype.ClientWithList[*corev1alpha.CloudMonitoringIntegration, *corev1alpha.CloudMonitoringIntegrationList]
}

// newCloudMonitoringIntegrations returns a CloudMonitoringIntegrations
func newCloudMonitoringIntegrations(c *CoreV1alphaClient) *cloudMonitoringIntegrations {
	return &cloudMonitoringIntegrations{
		gentype.NewClientWithList[*corev1alpha.CloudMonitoringIntegration, *corev1alpha.CloudMonitoringIntegrationList](
			"cloudmonitoringintegrations",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *corev1alpha.CloudMonitoringIntegration { return &corev1alpha.CloudMonitoringIntegration{} },
			func() *corev1alpha.CloudMonitoringIntegrationList {
				return &corev1alpha.CloudMonitoringIntegrationList{}
			},
		),
	}
}
