/*
Copyright 2026 Apoxy, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha

import (
	context "context"

	corev1alpha "github.com/apoxy-dev/apoxy/api/core/v1alpha"
	scheme "github.com/apoxy-dev/apoxy/client/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// DomainsGetter has a method to return a DomainInterface.
// A group's client should implement this interface.
type DomainsGetter interface {
	Domains() DomainInterface
}

// DomainInterface has methods to work with Domain resources.
type DomainInterface interface {
	Create(ctx context.Context, domain *corev1alpha.Domain, opts v1.CreateOptions) (*corev1alpha.Domain, error)
	Update(ctx context.Context, domain *corev1alpha.Domain, opts v1.UpdateOptions) (*corev1alpha.Domain, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, domain *corev1alpha.Domain, opts v1.UpdateOptions) (*corev1alpha.Domain, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*corev1alpha.Domain, error)
	List(ctx context.Context, opts v1.ListOptions) (*corev1alpha.DomainList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *corev1alpha.Domain, err error)
	DomainExpansion
}

// domains implements DomainInterface
type domains struct {
	*gentype.ClientWithList[*corev1alpha.Domain, *corev1alpha.DomainList]
}

// newDomains returns a Domains
func newDomains(c *CoreV1alphaClient) *domains {
	return &domains{
		gentype.NewClientWithList[*corev1alpha.Domain, *corev1alpha.DomainList](
			"domains",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *corev1alpha.Domain { return &corev1alpha.Domain{} },
			func() *corev1alpha.DomainList { return &corev1alpha.DomainList{} },
		),
	}
}
