/*
Copyright 2026 Apoxy, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha

import (
	context "context"

	corev1alpha "github.com/apoxy-dev/apoxy/api/core/v1alpha"
	scheme "github.com/apoxy-dev/apoxy/client/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// DomainZonesGetter has a method to return a DomainZoneInterface.
// A group's client should implement this interface.
type DomainZonesGetter interface {
	DomainZones() DomainZoneInterface
}

// DomainZoneInterface has methods to work with DomainZone resources.
type DomainZoneInterface interface {
	Create(ctx context.Context, domainZone *corev1alpha.DomainZone, opts v1.CreateOptions) (*corev1alpha.DomainZone, error)
	Update(ctx context.Context, domainZone *corev1alpha.DomainZone, opts v1.UpdateOptions) (*corev1alpha.DomainZone, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, domainZone *corev1alpha.DomainZone, opts v1.UpdateOptions) (*corev1alpha.DomainZone, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*corev1alpha.DomainZone, error)
	List(ctx context.Context, opts v1.ListOptions) (*corev1alpha.DomainZoneList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *corev1alpha.DomainZone, err error)
	DomainZoneExpansion
}

// domainZones implements DomainZoneInterface
type domainZones struct {
	*gentype.ClientWithList[*corev1alpha.DomainZone, *corev1alpha.DomainZoneList]
}

// newDomainZones returns a DomainZones
func newDomainZones(c *CoreV1alphaClient) *domainZones {
	return &domainZones{
		gentype.NewClientWithList[*corev1alpha.DomainZone, *corev1alpha.DomainZoneList](
			"domainzones",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *corev1alpha.DomainZone { return &corev1alpha.DomainZone{} },
			func() *corev1alpha.DomainZoneList { return &corev1alpha.DomainZoneList{} },
		),
	}
}
