/*
Copyright 2026 Apoxy, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha

import (
	context "context"

	corev1alpha "github.com/apoxy-dev/apoxy/api/core/v1alpha"
	scheme "github.com/apoxy-dev/apoxy/client/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// TunnelNodesGetter has a method to return a TunnelNodeInterface.
// A group's client should implement this interface.
type TunnelNodesGetter interface {
	TunnelNodes() TunnelNodeInterface
}

// TunnelNodeInterface has methods to work with TunnelNode resources.
type TunnelNodeInterface interface {
	Create(ctx context.Context, tunnelNode *corev1alpha.TunnelNode, opts v1.CreateOptions) (*corev1alpha.TunnelNode, error)
	Update(ctx context.Context, tunnelNode *corev1alpha.TunnelNode, opts v1.UpdateOptions) (*corev1alpha.TunnelNode, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, tunnelNode *corev1alpha.TunnelNode, opts v1.UpdateOptions) (*corev1alpha.TunnelNode, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*corev1alpha.TunnelNode, error)
	List(ctx context.Context, opts v1.ListOptions) (*corev1alpha.TunnelNodeList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *corev1alpha.TunnelNode, err error)
	TunnelNodeExpansion
}

// tunnelNodes implements TunnelNodeInterface
type tunnelNodes struct {
	*gentype.ClientWithList[*corev1alpha.TunnelNode, *corev1alpha.TunnelNodeList]
}

// newTunnelNodes returns a TunnelNodes
func newTunnelNodes(c *CoreV1alphaClient) *tunnelNodes {
	return &tunnelNodes{
		gentype.NewClientWithList[*corev1alpha.TunnelNode, *corev1alpha.TunnelNodeList](
			"tunnelnodes",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *corev1alpha.TunnelNode { return &corev1alpha.TunnelNode{} },
			func() *corev1alpha.TunnelNodeList { return &corev1alpha.TunnelNodeList{} },
		),
	}
}
