apiVersion: v1
kind: Service
metadata:
  name: {{ include "apoxy-gateway.fullname" . }}-apiserver-headless
  labels:
    {{- include "apoxy-gateway.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.apiserver.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "apoxy-gateway.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "apoxy-gateway.fullname" . }}-apiserver
  labels:
    {{- include "apoxy-gateway.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.apiserver.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "apoxy-gateway.selectorLabels" . | nindent 4 }}

