apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha.core.apoxy.dev
spec:
  group: core.apoxy.dev
  version: v1alpha
  groupPriorityMinimum: 1000
  versionPriority: 15
  insecureSkipTLSVerify: true
  service:
    name: {{ include "apoxy-gateway.fullname" . }}-apiserver
    namespace: {{ .Release.Namespace }}
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.extensions.apoxy.dev
spec:
  group: extensions.apoxy.dev
  version: v1alpha1
  groupPriorityMinimum: 1000
  versionPriority: 15
  insecureSkipTLSVerify: true
  service:
    name: {{ include "apoxy-gateway.fullname" . }}-apiserver
    namespace: {{ .Release.Namespace }}
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1.gateway.apoxy.dev
spec:
  group: gateway.apoxy.dev
  version: v1
  groupPriorityMinimum: 1000
  versionPriority: 15
  insecureSkipTLSVerify: true
  service:
    name: {{ include "apoxy-gateway.fullname" . }}-apiserver
    namespace: {{ .Release.Namespace }}
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.controllers.apoxy.dev
spec:
  group: controllers.apoxy.dev
  version: v1alpha1
  groupPriorityMinimum: 1000
  versionPriority: 15
  insecureSkipTLSVerify: true
  service:
    name: {{ include "apoxy-gateway.fullname" . }}-apiserver
    namespace: {{ .Release.Namespace }}
