apiVersion: v1
kind: Service
metadata:
  name: {{ include "apoxy-gateway.fullname" . }}
  namespace: {{ include "apoxy-gateway.namespace" . }}
  annotations:
    {{- .Values.backplane.service.annotations | toYaml | nindent 4 }}
  labels:
    {{- include "apoxy-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backplane.service.type }}
  {{- with .Values.backplane.service.sourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  externalTrafficPolicy: {{ .Values.backplane.service.externalTrafficPolicy }}
  ports:
  {{- with .Values.backplane.proxy.listeners }}
  {{- range . }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ if lt .port 1024 }}{{ add .port 10000 }}{{ else }}{{ .port }}{{ end }}
      protocol: {{ .protocol }}
  {{- end }}
  {{- end }}
  selector:
    {{- include "apoxy-gateway.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backplane
