apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "apoxy-gateway.fullname" . }}-proxy
  namespace: {{ include "apoxy-gateway.namespace" . }}
  labels:
    {{- include "apoxy-gateway.labels" . | nindent 4 }}
data:
  proxy.yaml: |-
    apiVersion: controllers.apoxy.dev/v1alpha1
    kind: Proxy
    metadata:
      name: {{ .Values.backplane.proxy.name }}
    spec:
      provider: unmanaged
      # Helm is trash: https://github.com/Masterminds/sprig/issues/269
      drainTimeout: {{ duration (.Values.backplane.proxy.drainTimeoutSeconds | toString) }}
      listeners:
        - name: https
          protocol: TCP
          port: {{ .Values.backplane.service.port }}
        - name: internal
          protocol: TCP
          port: {{ .Values.backplane.proxy.internalPort }}
      {{- with .Values.backplane.proxy.extraListeners }}
        {{- toYaml . | nindent 8 }}
      {{- end }}

