apiVersion: v1
kind: Service
metadata:
  name: {{ include "apoxy-gateway.fullname" . }}
  namespace: {{ include "apoxy-gateway.namespace" . }}
  annotations:
    {{ .Values.backplane.service.annotations | toYaml | nindent 4 }}
  labels:
    {{- include "apoxy-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backplane.service.type }}
  ports:
    - port: {{ .Values.backplane.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "apoxy-gateway.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backplane
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "apoxy-gateway.fullname" . }}-internal
  namespace: {{ include "apoxy-gateway.namespace" . }}
  labels:
    {{- include "apoxy-gateway.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.backplane.proxy.internalPort }}
      targetPort: internal
      protocol: TCP
      name: internal
  selector:
    {{- include "apoxy-gateway.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backplane
