{{- if .Values.kubeController.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "apoxy-gateway.fullname" . }}-kube-controller
  namespace: {{ include "apoxy-gateway.namespace" . }}
  labels:
    {{- include "apoxy-gateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: kube-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "apoxy-gateway.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: kube-controller
  template:
    metadata:
      {{- with .Values.kubeController.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "apoxy-gateway.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: kube-controller
    spec:
      {{- with .Values.kubeController.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ default (printf "%s-kube-controller" (include "apoxy-gateway.fullname" .)) .Values.kubeController.serviceAccount.name }}
      containers:
        - name: kube-controller
          image: "{{ .Values.kubeController.image.repository }}:{{ .Values.kubeController.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.kubeController.image.pullPolicy }}
          args:
            - run
            - --config
            - /etc/apoxy/config.yaml
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - name: api-proxy
              containerPort: 8443
              protocol: TCP
          resources:
            {{- toYaml .Values.kubeController.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/apoxy/config.yaml
              subPath: config.yaml
              readOnly: true
      {{- with .Values.kubeController.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kubeController.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kubeController.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "apoxy-gateway.fullname" . }}-kube-controller
{{- end }}
