/*
Copyright 2026 Apoxy, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apivpcv1alpha1 "github.com/apoxy-dev/apoxy/api/vpc/v1alpha1"
	internalinterfaces "github.com/apoxy-dev/apoxy/client/informers/internalinterfaces"
	vpcv1alpha1 "github.com/apoxy-dev/apoxy/client/listers/vpc/v1alpha1"
	versioned "github.com/apoxy-dev/apoxy/client/versioned"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// VPCServiceInformer provides access to a shared informer and lister for
// VPCServices.
type VPCServiceInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() vpcv1alpha1.VPCServiceLister
}

type vPCServiceInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewVPCServiceInformer constructs a new informer for VPCService type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewVPCServiceInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredVPCServiceInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredVPCServiceInformer constructs a new informer for VPCService type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredVPCServiceInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.VpcV1alpha1().VPCServices().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.VpcV1alpha1().VPCServices().Watch(context.TODO(), options)
			},
		},
		&apivpcv1alpha1.VPCService{},
		resyncPeriod,
		indexers,
	)
}

func (f *vPCServiceInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredVPCServiceInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *vPCServiceInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apivpcv1alpha1.VPCService{}, f.defaultInformer)
}

func (f *vPCServiceInformer) Lister() vpcv1alpha1.VPCServiceLister {
	return vpcv1alpha1.NewVPCServiceLister(f.Informer().GetIndexer())
}
