// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by protoc-gen-go-vpcrpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-vpcrpc v0.1.0
// - protoc               v5.28.3
// source: proto/vpc/datapath/v1/mesh.proto

package datapathv1

import (
	context "context"
	rpc "github.com/apoxy-dev/apoxy/pkg/vpc/rpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// Full method names of the Mesh service.
const (
	Mesh_Open_FullMethodName      = "/apoxy.vpc.datapath.v1.Mesh/Open"
	Mesh_Presence_FullMethodName  = "/apoxy.vpc.datapath.v1.Mesh/Presence"
	Mesh_SPIRows_FullMethodName   = "/apoxy.vpc.datapath.v1.Mesh/SPIRows"
	Mesh_TrunkKeys_FullMethodName = "/apoxy.vpc.datapath.v1.Mesh/TrunkKeys"
)

// MeshClient is the client API of the Mesh service.
type MeshClient interface {
	// Open is the first call on a session. The relay that dialed calls it.
	Open(ctx context.Context, in *MeshOpenRequest) (*MeshOpenResponse, error)
	// Presence sends the attachments of the caller: the full set, then each
	// change. The caller opens it one time on a session.
	Presence(ctx context.Context) (rpc.ClientStreamClient[PresenceUpdate, emptypb.Empty], error)
	// SPIRows copies SPI rows to the relay of the receiver.
	SPIRows(ctx context.Context) (rpc.ClientStreamClient[SPIRowUpdate, emptypb.Empty], error)
	// TrunkKeys gives the peer relay trunk SAs for traffic to the caller.
	TrunkKeys(ctx context.Context, in *KeysRequest) (*KeysResponse, error)
}

type meshClient struct{ c rpc.Caller }

// NewMeshClient returns a client of the Mesh service that makes calls with c.
func NewMeshClient(c rpc.Caller) MeshClient { return meshClient{c} }

func (c meshClient) Open(ctx context.Context, in *MeshOpenRequest) (*MeshOpenResponse, error) {
	out := new(MeshOpenResponse)
	if err := c.c.Invoke(ctx, Mesh_Open_FullMethodName, in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c meshClient) Presence(ctx context.Context) (rpc.ClientStreamClient[PresenceUpdate, emptypb.Empty], error) {
	return rpc.OpenClientStream[PresenceUpdate, emptypb.Empty](ctx, c.c, Mesh_Presence_FullMethodName)
}

func (c meshClient) SPIRows(ctx context.Context) (rpc.ClientStreamClient[SPIRowUpdate, emptypb.Empty], error) {
	return rpc.OpenClientStream[SPIRowUpdate, emptypb.Empty](ctx, c.c, Mesh_SPIRows_FullMethodName)
}

func (c meshClient) TrunkKeys(ctx context.Context, in *KeysRequest) (*KeysResponse, error) {
	out := new(KeysResponse)
	if err := c.c.Invoke(ctx, Mesh_TrunkKeys_FullMethodName, in, out); err != nil {
		return nil, err
	}
	return out, nil
}

// MeshServer is the server API of the Mesh service.
type MeshServer interface {
	// Open is the first call on a session. The relay that dialed calls it.
	Open(context.Context, *MeshOpenRequest) (*MeshOpenResponse, error)
	// Presence sends the attachments of the caller: the full set, then each
	// change. The caller opens it one time on a session.
	Presence(context.Context, rpc.ClientStreamServer[PresenceUpdate]) (*emptypb.Empty, error)
	// SPIRows copies SPI rows to the relay of the receiver.
	SPIRows(context.Context, rpc.ClientStreamServer[SPIRowUpdate]) (*emptypb.Empty, error)
	// TrunkKeys gives the peer relay trunk SAs for traffic to the caller.
	TrunkKeys(context.Context, *KeysRequest) (*KeysResponse, error)
}

// UnimplementedMeshServer returns Unimplemented for each method. Embed it to add
// methods to the service without a build failure.
type UnimplementedMeshServer struct{}

func (UnimplementedMeshServer) Open(context.Context, *MeshOpenRequest) (*MeshOpenResponse, error) {
	return nil, rpc.Errorf(rpc.Unimplemented, "method Open not implemented")
}

func (UnimplementedMeshServer) Presence(context.Context, rpc.ClientStreamServer[PresenceUpdate]) (*emptypb.Empty, error) {
	return nil, rpc.Errorf(rpc.Unimplemented, "method Presence not implemented")
}

func (UnimplementedMeshServer) SPIRows(context.Context, rpc.ClientStreamServer[SPIRowUpdate]) (*emptypb.Empty, error) {
	return nil, rpc.Errorf(rpc.Unimplemented, "method SPIRows not implemented")
}

func (UnimplementedMeshServer) TrunkKeys(context.Context, *KeysRequest) (*KeysResponse, error) {
	return nil, rpc.Errorf(rpc.Unimplemented, "method TrunkKeys not implemented")
}

// RegisterMeshServer adds the methods of srv to m.
func RegisterMeshServer(m *rpc.Mux, srv MeshServer) {
	rpc.HandleUnary(m, Mesh_Open_FullMethodName, srv.Open)
	rpc.HandleClientStream(m, Mesh_Presence_FullMethodName, srv.Presence)
	rpc.HandleClientStream(m, Mesh_SPIRows_FullMethodName, srv.SPIRows)
	rpc.HandleUnary(m, Mesh_TrunkKeys_FullMethodName, srv.TrunkKeys)
}
