// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by protoc-gen-go-vpcrpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-vpcrpc v0.1.0
// - protoc               v5.28.3
// source: proto/vpc/datapath/v1/peer.proto

package datapathv1

import (
	context "context"
	rpc "github.com/apoxy-dev/apoxy/pkg/vpc/rpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// Full method names of the Peer service.
const (
	Peer_Open_FullMethodName  = "/apoxy.vpc.datapath.v1.Peer/Open"
	Peer_Keys_FullMethodName  = "/apoxy.vpc.datapath.v1.Peer/Keys"
	Peer_Paths_FullMethodName = "/apoxy.vpc.datapath.v1.Peer/Paths"
)

// PeerClient is the client API of the Peer service.
type PeerClient interface {
	// Open is the first call on a session. The dialer calls it.
	Open(ctx context.Context, in *OpenRequest) (*OpenResponse, error)
	// Keys gives the peer SAs for traffic to the caller. The receiver calls it.
	Keys(ctx context.Context, in *KeysRequest) (*KeysResponse, error)
	// Paths sends the candidate sets of the caller. Each agent calls it once and
	// sends a new set when its addresses change.
	Paths(ctx context.Context) (rpc.ClientStreamClient[Candidates, emptypb.Empty], error)
}

type peerClient struct{ c rpc.Caller }

// NewPeerClient returns a client of the Peer service that makes calls with c.
func NewPeerClient(c rpc.Caller) PeerClient { return peerClient{c} }

func (c peerClient) Open(ctx context.Context, in *OpenRequest) (*OpenResponse, error) {
	out := new(OpenResponse)
	if err := c.c.Invoke(ctx, Peer_Open_FullMethodName, in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c peerClient) Keys(ctx context.Context, in *KeysRequest) (*KeysResponse, error) {
	out := new(KeysResponse)
	if err := c.c.Invoke(ctx, Peer_Keys_FullMethodName, in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c peerClient) Paths(ctx context.Context) (rpc.ClientStreamClient[Candidates, emptypb.Empty], error) {
	return rpc.OpenClientStream[Candidates, emptypb.Empty](ctx, c.c, Peer_Paths_FullMethodName)
}

// PeerServer is the server API of the Peer service.
type PeerServer interface {
	// Open is the first call on a session. The dialer calls it.
	Open(context.Context, *OpenRequest) (*OpenResponse, error)
	// Keys gives the peer SAs for traffic to the caller. The receiver calls it.
	Keys(context.Context, *KeysRequest) (*KeysResponse, error)
	// Paths sends the candidate sets of the caller. Each agent calls it once and
	// sends a new set when its addresses change.
	Paths(context.Context, rpc.ClientStreamServer[Candidates]) (*emptypb.Empty, error)
}

// UnimplementedPeerServer returns Unimplemented for each method. Embed it to add
// methods to the service without a build failure.
type UnimplementedPeerServer struct{}

func (UnimplementedPeerServer) Open(context.Context, *OpenRequest) (*OpenResponse, error) {
	return nil, rpc.Errorf(rpc.Unimplemented, "method Open not implemented")
}

func (UnimplementedPeerServer) Keys(context.Context, *KeysRequest) (*KeysResponse, error) {
	return nil, rpc.Errorf(rpc.Unimplemented, "method Keys not implemented")
}

func (UnimplementedPeerServer) Paths(context.Context, rpc.ClientStreamServer[Candidates]) (*emptypb.Empty, error) {
	return nil, rpc.Errorf(rpc.Unimplemented, "method Paths not implemented")
}

// RegisterPeerServer adds the methods of srv to m.
func RegisterPeerServer(m *rpc.Mux, srv PeerServer) {
	rpc.HandleUnary(m, Peer_Open_FullMethodName, srv.Open)
	rpc.HandleUnary(m, Peer_Keys_FullMethodName, srv.Keys)
	rpc.HandleClientStream(m, Peer_Paths_FullMethodName, srv.Paths)
}
