// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by protoc-gen-go-vpcrpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-vpcrpc v0.1.0
// - protoc               v5.28.3
// source: proto/vpc/datapath/v1/relay.proto

package datapathv1

import (
	context "context"
	rpc "github.com/apoxy-dev/apoxy/pkg/vpc/rpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// Full method names of the Relay service.
const (
	Relay_Session_FullMethodName       = "/apoxy.vpc.datapath.v1.Relay/Session"
	Relay_Attach_FullMethodName        = "/apoxy.vpc.datapath.v1.Relay/Attach"
	Relay_Rekey_FullMethodName         = "/apoxy.vpc.datapath.v1.Relay/Rekey"
	Relay_ResolvePeer_FullMethodName   = "/apoxy.vpc.datapath.v1.Relay/ResolvePeer"
	Relay_RegisterSPI_FullMethodName   = "/apoxy.vpc.datapath.v1.Relay/RegisterSPI"
	Relay_UnregisterSPI_FullMethodName = "/apoxy.vpc.datapath.v1.Relay/UnregisterSPI"
)

// RelayClient is the client API of the Relay service.
type RelayClient interface {
	// Session starts with Hello and Welcome, then carries Sync. The relay sends
	// routes, NoRoute, key changes, config and drain. The agent sends Ack and Status.
	Session(ctx context.Context) (rpc.BidiStreamClient[SessionRequest, SessionResponse], error)
	// Attach adds an attachment to the session.
	Attach(ctx context.Context, in *AttachRequest) (*AttachResponse, error)
	// Rekey gives the relay SAs for traffic from the relay to the agent.
	Rekey(ctx context.Context, in *KeysRequest) (*KeysResponse, error)
	// ResolvePeer finds how the relay reaches an address. Errors: NotFound,
	// PermissionDenied.
	ResolvePeer(ctx context.Context, in *ResolvePeerRequest) (*ResolvePeerResponse, error)
	// RegisterSPI adds forward rows for SPIs that a receiver gave to the caller.
	RegisterSPI(ctx context.Context, in *RegisterSPIRequest) (*emptypb.Empty, error)
	// UnregisterSPI removes forward rows of the caller.
	UnregisterSPI(ctx context.Context, in *UnregisterSPIRequest) (*emptypb.Empty, error)
}

type relayClient struct{ c rpc.Caller }

// NewRelayClient returns a client of the Relay service that makes calls with c.
func NewRelayClient(c rpc.Caller) RelayClient { return relayClient{c} }

func (c relayClient) Session(ctx context.Context) (rpc.BidiStreamClient[SessionRequest, SessionResponse], error) {
	return rpc.OpenBidiStream[SessionRequest, SessionResponse](ctx, c.c, Relay_Session_FullMethodName)
}

func (c relayClient) Attach(ctx context.Context, in *AttachRequest) (*AttachResponse, error) {
	out := new(AttachResponse)
	if err := c.c.Invoke(ctx, Relay_Attach_FullMethodName, in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c relayClient) Rekey(ctx context.Context, in *KeysRequest) (*KeysResponse, error) {
	out := new(KeysResponse)
	if err := c.c.Invoke(ctx, Relay_Rekey_FullMethodName, in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c relayClient) ResolvePeer(ctx context.Context, in *ResolvePeerRequest) (*ResolvePeerResponse, error) {
	out := new(ResolvePeerResponse)
	if err := c.c.Invoke(ctx, Relay_ResolvePeer_FullMethodName, in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c relayClient) RegisterSPI(ctx context.Context, in *RegisterSPIRequest) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	if err := c.c.Invoke(ctx, Relay_RegisterSPI_FullMethodName, in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c relayClient) UnregisterSPI(ctx context.Context, in *UnregisterSPIRequest) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	if err := c.c.Invoke(ctx, Relay_UnregisterSPI_FullMethodName, in, out); err != nil {
		return nil, err
	}
	return out, nil
}

// RelayServer is the server API of the Relay service.
type RelayServer interface {
	// Session starts with Hello and Welcome, then carries Sync. The relay sends
	// routes, NoRoute, key changes, config and drain. The agent sends Ack and Status.
	Session(context.Context, rpc.BidiStreamServer[SessionRequest, SessionResponse]) error
	// Attach adds an attachment to the session.
	Attach(context.Context, *AttachRequest) (*AttachResponse, error)
	// Rekey gives the relay SAs for traffic from the relay to the agent.
	Rekey(context.Context, *KeysRequest) (*KeysResponse, error)
	// ResolvePeer finds how the relay reaches an address. Errors: NotFound,
	// PermissionDenied.
	ResolvePeer(context.Context, *ResolvePeerRequest) (*ResolvePeerResponse, error)
	// RegisterSPI adds forward rows for SPIs that a receiver gave to the caller.
	RegisterSPI(context.Context, *RegisterSPIRequest) (*emptypb.Empty, error)
	// UnregisterSPI removes forward rows of the caller.
	UnregisterSPI(context.Context, *UnregisterSPIRequest) (*emptypb.Empty, error)
}

// UnimplementedRelayServer returns Unimplemented for each method. Embed it to add
// methods to the service without a build failure.
type UnimplementedRelayServer struct{}

func (UnimplementedRelayServer) Session(context.Context, rpc.BidiStreamServer[SessionRequest, SessionResponse]) error {
	return rpc.Errorf(rpc.Unimplemented, "method Session not implemented")
}

func (UnimplementedRelayServer) Attach(context.Context, *AttachRequest) (*AttachResponse, error) {
	return nil, rpc.Errorf(rpc.Unimplemented, "method Attach not implemented")
}

func (UnimplementedRelayServer) Rekey(context.Context, *KeysRequest) (*KeysResponse, error) {
	return nil, rpc.Errorf(rpc.Unimplemented, "method Rekey not implemented")
}

func (UnimplementedRelayServer) ResolvePeer(context.Context, *ResolvePeerRequest) (*ResolvePeerResponse, error) {
	return nil, rpc.Errorf(rpc.Unimplemented, "method ResolvePeer not implemented")
}

func (UnimplementedRelayServer) RegisterSPI(context.Context, *RegisterSPIRequest) (*emptypb.Empty, error) {
	return nil, rpc.Errorf(rpc.Unimplemented, "method RegisterSPI not implemented")
}

func (UnimplementedRelayServer) UnregisterSPI(context.Context, *UnregisterSPIRequest) (*emptypb.Empty, error) {
	return nil, rpc.Errorf(rpc.Unimplemented, "method UnregisterSPI not implemented")
}

// RegisterRelayServer adds the methods of srv to m.
func RegisterRelayServer(m *rpc.Mux, srv RelayServer) {
	rpc.HandleBidiStream(m, Relay_Session_FullMethodName, srv.Session)
	rpc.HandleUnary(m, Relay_Attach_FullMethodName, srv.Attach)
	rpc.HandleUnary(m, Relay_Rekey_FullMethodName, srv.Rekey)
	rpc.HandleUnary(m, Relay_ResolvePeer_FullMethodName, srv.ResolvePeer)
	rpc.HandleUnary(m, Relay_RegisterSPI_FullMethodName, srv.RegisterSPI)
	rpc.HandleUnary(m, Relay_UnregisterSPI_FullMethodName, srv.UnregisterSPI)
}
